### ISSUE TITLE
[WinError 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by JEONGHA-SHIN** [jhj0517/Whisper-WebUI#127]
**- OS:  Windows 10
I am facing the following error. It's difficult to figure out what the problem is.
I would really appreciate it if you could tell me the solution.**

Error transcribing file: [WinError 2] The system cannot find the file specified
Traceback (most recent call last):
  File "D:\Dev\Whisper-WebUI\venv\Lib\site-packages\gradio\queueing.py", line 495, in call_prediction
    output = await route_utils.call_process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Dev\Whisper-WebUI\venv\Lib\site-packages\gradio\route_utils.py", line 232, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Dev\Whisper-WebUI\venv\Lib\site-packages\gradio\blocks.py", line 1570, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Dev\Whisper-WebUI\venv\Lib\site-packages\gradio\blocks.py", line 1397, in postprocess_data
    self.validate_outputs(fn_index, predictions)  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Dev\Whisper-WebUI\venv\Lib\site-packages\gradio\blocks.py", line 1371, in validate_outputs
    raise ValueError(
ValueError: An event handler (transcribe_file) didn't receive enough output values (needed: 2, received: 1).
Wanted outputs:
    [textbox, file]
Received outputs:
    [None]

**Comment by jhj0517** [comment]
Hi, According to [gradio #2986](https://github.com/gradio-app/gradio/issues/2986), it seems that some JavaScript is problematic on your browser to run gradio .
To fix this, 

1. Disable All Chrome Extensions : some extensions may contain problematic JavaScript

or simply

2. Use a Different Browser: If you're using Chrome, try different browser, such as Edge.
