### ISSUE TITLE
cannot start beacuse 'TypeError: argument of type 'NoneType' is not iterable'

### ISSUE THREAD

**Issue by onkenut** [jhj0517/Whisper-WebUI#133]
PS D:\Whisper\webUI\Whisper-WebUI-master> & D:/python/python.exe d:/Whisper/webUI/Whisper-WebUI-master/app.py
Traceback (most recent call last):
  File "d:\Whisper\webUI\Whisper-WebUI-master\app.py", line 5, in <module>
    from modules.whisper_Inference import WhisperInference
  File "d:\Whisper\webUI\Whisper-WebUI-master\modules\whisper_Inference.py", line 1, in <module>
    import whisper
  File "D:\python\lib\site-packages\whisper.py", line 69, in <module>
    libc = ctypes.CDLL(libc_name)
  File "D:\python\lib\ctypes\__init__.py", line 364, in __init__
    if '/' in name or '\\' in name:
TypeError: argument of type 'NoneType' is not iterable

**Comment by jhj0517** [comment]
Hi! 
According to [whisper discussion #696](https://github.com/openai/whisper/discussions/696),  Did you install your whisper manually and not `pip install -r requirements.txt` ? 

You should've
```
pip uninstall whisper
pip install openai-whisper
```
`whipser` is a different package than `openai-whisper`.

**Comment by onkenut** [comment]
that's ok ! thanks！
