### ISSUE TITLE
You are using gradio version 4.14.0, however version 4.29.0 is available, please upgrade.

### ISSUE THREAD

**Issue by che2ze** [jhj0517/Whisper-WebUI#166]
**Which OS are you using?**
 - OS: [e.g. iOS or Windows.. If you are using Google Colab, just Colab.]
Google Colab
2024-06-07 09:48:55.286611: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-06-07 09:48:55.286669: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-06-07 09:48:55.288583: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-06-07 09:48:55.299325: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-06-07 09:48:57.098308: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Traceback (most recent call last):
  File "/content/Whisper-WebUI/app.py", line 349, in <module>
    app = App(args=_args)
  File "/content/Whisper-WebUI/app.py", line 19, in __init__
    self.whisper_inf = WhisperInference() if self.args.disable_faster_whisper else FasterWhisperInference()
  File "/content/Whisper-WebUI/modules/faster_whisper_inference.py", line 29, in __init__
    self.model_paths = self.get_model_paths()
  File "/content/Whisper-WebUI/modules/faster_whisper_inference.py", line 340, in get_model_paths
    existing_models = os.listdir(self.model_dir)
FileNotFoundError: [Errno 2] No such file or directory: 'models/Whisper/faster-whisper'
IMPORTANT: You are using gradio version 4.14.0, however version 4.29.0 is available, please upgrade.

**Comment by jhj0517** [comment]
Hi, This is fixed in #167, 
Please re-open and let me know if it persists!
