### ISSUE TITLE
WhisperX - Speaker Diarization

### ISSUE THREAD

**Issue by mjtechguy** [jhj0517/Whisper-WebUI#168]
I think it would be great to be able to leverage WhisperX and speaker diarization. Any plans to do this?

https://github.com/m-bain/whisperX

**Comment by jhj0517** [comment]
Hi, I've made a TODO list in the README and added it. 
I'll work on it later!

**Comment by jhj0517** [comment]
I'm testing whisperX and listing some issues here:

- Incompatible torch version
   - whisperX models were trained on `torch 1.10.0+cu102` and this WebUI uses `torch 2.3.1+cu121`
- Slow transcription
    - This may be due to an incompatible torch, but it was much slower than other implementations. <br>`16.5 sec` for 30 secs of audio input with `large-v2`

**Comment by moda20** [comment]
@jhj0517 looking at the speaker diarization it seems that it uses a different model from HF, so it can be integrated without the whisperX model
@mjtechguy

**Comment by jhj0517** [comment]
Yes, it seems that whisperX just passes the diarized result to faster-whisper.
So I think I should modularize the diarization and integrate it with faster-whisper.

**Comment by moda20** [comment]
@jhj0517 trying the latest version with diarization, but I am getting this error, it seems it downloaded the model but it didn't finish the diarization. 

```
2024-06-26T19:36:55.526316618Z Traceback (most recent call last):
2024-06-26T19:36:55.526636537Z   File "/Whisper-WebUI/venv/lib/python3.11/site-packages/gradio/queueing.py", line 527, in process_events
2024-06-26T19:36:55.526654992Z     response = await route_utils.call_process_api(
2024-06-26T19:36:55.526661835Z                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-26T19:36:55.526667215Z   File "/Whisper-WebUI/venv/lib/python3.11/site-packages/gradio/route_utils.py", line 270, in call_process_api
2024-06-26T19:36:55.526672605Z     output = await app.get_blocks().process_api(
2024-06-26T19:36:55.526677936Z              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-26T19:36:55.526685630Z   File "/Whisper-WebUI/venv/lib/python3.11/site-packages/gradio/blocks.py", line 1856, in process_api
2024-06-26T19:36:55.526693645Z     data = await self.postprocess_data(fn_index, result["prediction"], state)
2024-06-26T19:36:55.526700999Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-26T19:36:55.526709536Z   File "/Whisper-WebUI/venv/lib/python3.11/site-packages/gradio/blocks.py", line 1634, in postprocess_data
2024-06-26T19:36:55.526717781Z     self.validate_outputs(fn_index, predictions)  # type: ignore
2024-06-26T19:36:55.526725736Z     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-26T19:36:55.526734253Z   File "/Whisper-WebUI/venv/lib/python3.11/site-packages/gradio/blocks.py", line 1610, in validate_outputs
2024-06-26T19:36:55.526743881Z     raise ValueError(
2024-06-26T19:36:55.526752507Z ValueError: An event handler (transcribe_file) didn't receive enough output values (needed: 2, received: 1).
2024-06-26T19:36:55.526760563Z Wanted outputs:
2024-06-26T19:36:55.526767927Z     [<gradio.components.textbox.Textbox object at 0x78caea9c2590>, <gradio.templates.Files object at 0x78caea231350>]
2024-06-26T19:36:55.526795169Z Received outputs:
2024-06-26T19:36:55.526800238Z     [None]
```

**Comment by jhj0517** [comment]
@moda20 Can you show the full log before the Traceback? 
This might happens when failed to load the model. 

To use pyannote model, you have to mannually go to 

1. https://huggingface.co/pyannote/speaker-diarization-3.1
2. https://huggingface.co/pyannote/segmentation-3.0

and accept their terms, and enter the Huggingface token.. 

It might be inconvenient but it's their requirements.

**Comment by moda20** [comment]
@jhj0517 Yes, accepting the conditions of the second segmentation HF model, did the trick. i didn't see it in the README, that's why

**Comment by jhj0517** [comment]
@moda20 Trying to run diarization models with CPU may help in that case. 
You can change the device in the dropdown.

![image](https://github.com/jhj0517/Whisper-WebUI/assets/97279763/1a8a6d26-e4bd-4af8-91e2-89655cabc92d)

**Comment by cookiexND** [comment]
When the file format is TXT, the first character of the output is hidden by the speaker delimiter
This may be difficult to understand in Japanese, but it is as follows.

w/ diarization:
SPEAKER_04|部科学省の数理データサイエンスAI教育プログラム認定制度に
SPEAKER_04|ータサイエンス教育プログラムの所持申請を行ったという報告がありまして、

w/o diarization:
文部科学省の数理データサイエンスAI教育プログラム認定制度に
データサイエンス教育プログラムの所持申請を行ったという報告がありまして、

**Comment by jhj0517** [comment]
@cookiexND Thanks for reporting this. It's fixed in #183 

@Tom-Neverwinter Can you provide more information about the error you received?

**Comment by moda20** [comment]
@linuxlurak the first error seems to be that the device to use for transcribing is not selected, be sure you have selected the cpu or gpu in the UI selector. 

the second error (`Received outputs: [None]`) is a higher level error that can be triggered by a multitude of issues.

**Comment by jhj0517** [comment]
Hi @linuxlurak.
I tried to fix the bug in #244, can you check the latest version?
You can update the WebUI with `update.sh`.
