### ISSUE TITLE
Traceback (most recent call last):

### ISSUE THREAD

**Issue by che2ze** [jhj0517/Whisper-WebUI#185]
**Which OS are you using?**
 - OS: [e.g. iOS or Windows.. If you are using Google Colab, just Colab.]
-> Google Colab

Traceback (most recent call last):
  File "/content/Whisper-WebUI/app.py", line 4, in <module>
    from modules.whisper.whisper_Inference import WhisperInference
  File "/content/Whisper-WebUI/modules/whisper/whisper_Inference.py", line 9, in <module>
    from modules.whisper.whisper_base import WhisperBase
  File "/content/Whisper-WebUI/modules/whisper/whisper_base.py", line 16, in <module>
    from modules.diarize.diarizer import Diarizer
  File "/content/Whisper-WebUI/modules/diarize/diarizer.py", line 7, in <module>
    from modules.diarize.diarize_pipeline import DiarizationPipeline, assign_word_speakers
  File "/content/Whisper-WebUI/modules/diarize/diarize_pipeline.py", line 4, in <module>
    from pyannote.audio import Pipeline
ModuleNotFoundError: No module named 'pyannote'
![스크린샷 2024-06-28 132347](https://github.com/jhj0517/Whisper-WebUI/assets/164759760/50f46d15-c310-4a09-9370-fc7344b06ea3)

**Comment by jhj0517** [comment]
Thanks for reporting this! 
Fixed in #186. 

Please re-open and let me know if the issue persists!
