### ISSUE TITLE
Docker Image

### ISSUE THREAD

**Issue by 9SMTM6** [jhj0517/Whisper-WebUI#192]
Heyo, has the docker image been tested as of late? I'm getting an error trying to run it:

```sh
 zsh❯ docker run --rm --runtime=nvidia --gpus all -v ${pwd}/whisper_models/:/Whisper-WebUI/models -v ${pwd}/subtitles/:/Whisper-WebUI/outputs -p 0.0.0.0:7860:7860 -it jhj0517/whisper-webui --server_name 0.0.0.0 --server_port 7860
Traceback (most recent call last):
  File "/Whisper-WebUI/app.py", line 438, in <module>
    app = App(args=_args)
          ^^^^^^^^^^^^^^^
  File "/Whisper-WebUI/app.py", line 18, in __init__
    self.whisper_inf = self.init_whisper()
                       ^^^^^^^^^^^^^^^^^^^
  File "/Whisper-WebUI/app.py", line 36, in init_whisper
    whisper_inf = FasterWhisperInference(
                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Whisper-WebUI/modules/whisper/faster_whisper_inference.py", line 31, in __init__
    self.available_compute_types = ctranslate2.get_supported_compute_types(
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: CUDA failed with error unknown error

```

Admittedly I've not yet run a lot of GPU workloads through docker on that desktop, but both non-dockerized pytorch workloads work fine, and when running nvidia-smi in another container it also works fine:

```sh
 zsh❯ docker run --rm --runtime=nvidia --gpus all nvidia/cuda:12.1.0-devel-ubuntu22.04 nvidia-smi

==========
== CUDA ==
==========

CUDA Version 12.1.0

Container image Copyright (c) 2016-2023, NVIDIA CORPORATION & AFFILIATES. All rights reserved.

This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license

A copy of this license is made available in this container at /NGC-DL-CONTAINER-LICENSE for your convenience.

*************************
** DEPRECATION NOTICE! **
*************************
THIS IMAGE IS DEPRECATED and is scheduled for DELETION.
    https://gitlab.com/nvidia/container-images/cuda/blob/master/doc/support-policy.md

Thu Jul  4 14:52:36 2024       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.67                 Driver Version: 550.67         CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 4070 ...    Off |   00000000:08:00.0 Off |                  N/A |
|  0%   34C    P8              3W /  285W |     168MiB /  16376MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
                                                                                         
+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
+-----------------------------------------------------------------------------------------+

``` 

Previously I've got other errors, but now I'm unable to reproduce these. At the time I did not pass the `--runtime=nvidia` parameter, but even a restart of docker did not allow me to reproduce these errors:

```
 zsh❯ sudo docker logs a3167147e5e92d007565589cf43692da72d8cd2622cf7d395eb276332a01bfaa
Use "faster-whisper" implementation
Device "cuda" is detected
Running on local URL:  http://0.0.0.0:7860

To create a public link, set `share=True` in `launch()`.
config.json: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2.80k/2.80k [00:00<00:00, 28.1MB/s]
vocabulary.txt: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 460k/460k [00:00<00:00, 1.25MB/s]
tokenizer.json: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2.20M/2.20M [00:01<00:00, 2.12MB/s]
model.bin:  15%|██████████████████▋                                                                                                          | 461M/3.09G [00:40<03:47, 11.5MB/s]sh: 1: start: not found█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2.20M/2.20M [00:01<00:00, 2.13MB/s]
model.bin:  15%|███████████████████                                                                                                          | 472M/3.09G [00:41<03:45, 11.6MB/s]sh: 1: start: not found
model.bin:  88%|████████████████████████████████████████████████���████████████████████████████████████████████████████████████               | 2.72G/3.09G [03:56<00:32, 11.4MB/model.bin: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3.09G/3.09G [04:29<00:00, 11.5MB/s]
Error transcribing file: CUDA failed with error CUDA-capable device(s) is/are busy or unavailable
Traceback (most recent call last):
  File "/Whisper-WebUI/venv/lib/python3.11/site-packages/gradio/queueing.py", line 527, in process_events
    response = await route_utils.call_process_api(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Whisper-WebUI/venv/lib/python3.11/site-packages/gradio/route_utils.py", line 270, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Whisper-WebUI/venv/lib/python3.11/site-packages/gradio/blocks.py", line 1856, in process_api
    data = await self.postprocess_data(fn_index, result["prediction"], state)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Whisper-WebUI/venv/lib/python3.11/site-packages/gradio/blocks.py", line 1634, in postprocess_data
    self.validate_outputs(fn_index, predictions)  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Whisper-WebUI/venv/lib/python3.11/site-packages/gradio/blocks.py", line 1610, in validate_outputs
    raise ValueError(
ValueError: An event handler (transcribe_file) didn't receive enough output values (needed: 2, received: 1).
Wanted outputs:
    [<gradio.components.textbox.Textbox object at 0x75f53942cb50>, <gradio.templates.Files object at 0x75f53946b410>]
Received outputs:
    [None]
Error transcribing file: CUDA failed with error CUDA-capable device(s) is/are busy or unavailable
Traceback (most recent call last):
  File "/Whisper-WebUI/venv/lib/python3.11/site-packages/gradio/queueing.py", line 527, in process_events
    response = await route_utils.call_process_api(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Whisper-WebUI/venv/lib/python3.11/site-packages/gradio/route_utils.py", line 270, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Whisper-WebUI/venv/lib/python3.11/site-packages/gradio/blocks.py", line 1856, in process_api
    data = await self.postprocess_data(fn_index, result["prediction"], state)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Whisper-WebUI/venv/lib/python3.11/site-packages/gradio/blocks.py", line 1634, in postprocess_data
    self.validate_outputs(fn_index, predictions)  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Whisper-WebUI/venv/lib/python3.11/site-packages/gradio/blocks.py", line 1610, in validate_outputs
    raise ValueError(
ValueError: An event handler (transcribe_file) didn't receive enough output values (needed: 2, received: 1).
Wanted outputs:
    [<gradio.components.textbox.Textbox object at 0x75f53942cb50>, <gradio.templates.Files object at 0x75f53946b410>]
Received outputs:
    [None]
Error transcribing file: CUDA failed with error CUDA-capable device(s) is/are busy or unavailable
Traceback (most recent call last):
  File "/Whisper-WebUI/venv/lib/python3.11/site-packages/gradio/queueing.py", line 527, in process_events
    response = await route_utils.call_process_api(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Whisper-WebUI/venv/lib/python3.11/site-packages/gradio/route_utils.py", line 270, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Whisper-WebUI/venv/lib/python3.11/site-packages/gradio/blocks.py", line 1856, in process_api
    data = await self.postprocess_data(fn_index, result["prediction"], state)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Whisper-WebUI/venv/lib/python3.11/site-packages/gradio/blocks.py", line 1634, in postprocess_data
    self.validate_outputs(fn_index, predictions)  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Whisper-WebUI/venv/lib/python3.11/site-packages/gradio/blocks.py", line 1610, in validate_outputs
    raise ValueError(
ValueError: An event handler (transcribe_file) didn't receive enough output values (needed: 2, received: 1).
Wanted outputs:
    [<gradio.components.textbox.Textbox object at 0x75f53942cb50>, <gradio.templates.Files object at 0x75f53946b410>]
Received outputs:
    [None]
config.json: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2.64k/2.64k [00:00<00:00, 26.6MB/s]
vocabulary.txt: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 422k/422k [00:00<00:00, 1.21MB/s]
tokenizer.json: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2.13M/2.13M [00:00<00:00, 2.59MB/s]
model.bin:  81%|████████���███████████████████████████████████████████████████████████████████████████████████████████▍                       | 1.24G/1.53G [02:18<00:25, 11.5MB/model.bin: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1.53G/1.53G [02:44<00:00, 9.27MB/s]
Error transcribing file: CUDA failed with error CUDA-capable device(s) is/are busy or unavailable
Traceback (most recent call last):
  File "/Whisper-WebUI/venv/lib/python3.11/site-packages/gradio/queueing.py", line 527, in process_events
    response = await route_utils.call_process_api(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Whisper-WebUI/venv/lib/python3.11/site-packages/gradio/route_utils.py", line 270, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Whisper-WebUI/venv/lib/python3.11/site-packages/gradio/blocks.py", line 1856, in process_api
    data = await self.postprocess_data(fn_index, result["prediction"], state)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Whisper-WebUI/venv/lib/python3.11/site-packages/gradio/blocks.py", line 1634, in postprocess_data
    self.validate_outputs(fn_index, predictions)  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Whisper-WebUI/venv/lib/python3.11/site-packages/gradio/blocks.py", line 1610, in validate_outputs
    raise ValueError(
ValueError: An event handler (transcribe_file) didn't receive enough output values (needed: 2, received: 1).
Wanted outputs:
    [<gradio.components.textbox.Textbox object at 0x75f53942cb50>, <gradio.templates.Files object at 0x75f53946b410>]
Received outputs:
    [None]

```

These downloads were caused by the initial request and then by me changing model as a test.
At that time I had only these small processes on the GPU, and the test I've done above also ran fine immediately afterwards:

```
 zsh❯ nvidia-smi
Thu Jul  4 16:59:41 2024       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.67                 Driver Version: 550.67         CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 4070 ...    Off |   00000000:08:00.0 Off |                  N/A |
|  0%   34C    P8              3W /  285W |     168MiB /  16376MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
                                                                                         
+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    0   N/A  N/A      1154      G   /usr/lib/xorg/Xorg                            146MiB |
|    0   N/A  N/A      2057      G   /usr/bin/gnome-shell                           11MiB |
+-----------------------------------------------------------------------------------------+

```

**Which OS are you using?**
 - OS: PopOS (latest stable)

**Comment by 9SMTM6** [comment]
Huh. I also tested it on my old PC/NAS with unraid and a GTX 1070, and I got it working.

After some crashes that were somewhat easy to debug when looking at the logs. The default compute type of float16 is not supported by the 1070, switching to float32 solved that. Generally error reporting could probably be improved, but I'm sure youve got that on your screen, and in the end this is very helpful already in its current state.

It has similar enough though slightly older nvidia drivers:

```sh
root@3LockedChest:/mnt/user/Disc-Rips# nvidia-smi
Thu Jul  4 17:14:39 2024       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.40.07              Driver Version: 550.40.07      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce GTX 1070        On  |   00000000:01:00.0 Off |                  N/A |
|  0%   36C    P8              8W /  200W |     426MiB /   8192MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
                                                                                         
+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    0   N/A  N/A     12340      C   python                                        424MiB |
+-----------------------------------------------------------------------------------------+
```

Not sure whats the difference here.

**Comment by jhj0517** [comment]
Thanks for reporting. 

I just tested with [jhj0517/whisper-webui](https://hub.docker.com/repository/docker/jhj0517/whisper-webui/general) and couldn't reproduce it on RTX 3060.
This seems to be related to CUDA detection, so I tried to mitigate it in #194

**Comment by 9SMTM6** [comment]
Oh wow, this seems to have really fixed it. At least I'm unable to reproduce either of both crashes!
