### ISSUE TITLE
Did not work in google colab even 1 week ago is working well !

### ISSUE THREAD

**Issue by haytam776** [jhj0517/Whisper-WebUI#203]
**Which OS are you using?**
 - OS: Colab 
 - 1 week ago, this awesome tool worked well for me in Google Colab, but today I ran it and it's not working anymore: 
 - 
 - ```
Error transcribing file: get_throttling_function_name: could not find match for multiple
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/gradio/queueing.py", line 527, in process_events
    response = await route_utils.call_process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/route_utils.py", line 270, in call_process_api
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1856, in process_api
    data = await self.postprocess_data(fn_index, result["prediction"], state)
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1634, in postprocess_data
    self.validate_outputs(fn_index, predictions)  # type: ignore
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1610, in validate_outputs
    raise ValueError(
ValueError: An event handler (transcribe_youtube) didn't receive enough output values (needed: 2, received: 1).
Wanted outputs:
    [<gradio.components.textbox.Textbox object at 0x7c485b3a1510>, <gradio.templates.Files object at 0x7c485b3a1570>]
Received outputs:
    [None]
Keyboard interruption in main thread... closing server.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 2553, in block_thread
    time.sleep(0.1)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/content/Whisper-WebUI/app.py", line 388, in <module>
    app.launch()
  File "/content/Whisper-WebUI/app.py", line 341, in launch
    self.app.queue(api_open=False).launch(**launch_args)
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 2458, in launch
    self.block_thread()
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 2557, in block_thread
    self.server.close()
  File "/usr/local/lib/python3.10/dist-packages/gradio/http_server.py", line 68, in close
    self.thread.join(timeout=5)
  File "/usr/lib/python3.10/threading.py", line 1100, in join
    self._wait_for_tstate_lock(timeout=max(timeout, 0))
  File "/usr/lib/python3.10/threading.py", line 1116, in _wait_for_tstate_lock
    if lock.acquire(block, timeout):
KeyboardInterrupt
Killing tunnel 127.0.0.1:7860 <>

```

**Comment by jhj0517** [comment]
@haytam776 Hi. This is the pytube bug from [pytube #1954](https://github.com/pytube/pytube/issues/1954).

Whenever youtube changes something in their frontend, pytube sometimes becomes problematic.
But based on my experience this kind of Regex bug get fixed very soon. ( like within a few days ).

It will be fixed when [pytube PR #1956](https://github.com/pytube/pytube/pull/1956) is merged. 

Until then, I will use the forked branch of pytube temporarily.

**Comment by haytam776** [comment]
Thank you so much its work now  😍
