### ISSUE TITLE
New error , even one week ago everything work fine when I click to transcribe botton

### ISSUE THREAD

**Issue by haytam776** [jhj0517/Whisper-WebUI#220]
**Which OS are you using?**
 - OS:COLAB
 - Hi, after you last update of this tools , there is a new error when I'm using insanely fast whisper 
 - `This share link expires in 72 hours. For free permanent hosting and GPU upgrades, run `gradio deploy` from Terminal to deploy to Spaces (https://huggingface.co/spaces)
Error transcribing file: HTTP Error 400: Bad Request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/gradio/queueing.py", line 527, in process_events
    response = await route_utils.call_process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/route_utils.py", line 270, in call_process_api
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1856, in process_api
    data = await self.postprocess_data(fn_index, result["prediction"], state)
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1634, in postprocess_data
    self.validate_outputs(fn_index, predictions)  # type: ignore
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1610, in validate_outputs
    raise ValueError(
ValueError: An event handler (transcribe_youtube) didn't receive enough output values (needed: 2, received: 1).
Wanted outputs:
    [<gradio.components.textbox.Textbox object at 0x7ff886a04970>, <gradio.templates.Files object at 0x7ff886a049d0>]
Received outputs:
    [None]`

**Comment by haytam776** [comment]
#203 this is the same problem I think even here is fixed

**Comment by jhj0517** [comment]
pytube issue is raised in 
- https://github.com/pytube/pytube/issues/1985

I will use [pytubefix](https://github.com/JuanBindez/pytubefix) until it is fixed in the official package.

**Comment by jhj0517** [comment]
Fixed in #221, Please let me know if the issue persists!
