### ISSUE TITLE
torch problem

### ISSUE THREAD

**Issue by hactuber** [jhj0517/Whisper-WebUI#240]
**Which OS are you using?**
 - OS: Windows 11
 
 Traceback (most recent call last):
  File "C:\Users\Adminstrator\Desktop\desk\Whisper-WebUI\app.py", line 5, in <module>
    from modules.whisper.whisper_factory import WhisperFactory
  File "C:\Users\Adminstrator\Desktop\desk\Whisper-WebUI\modules\whisper\whisper_factory.py", line 4, in <module>
    from modules.whisper.faster_whisper_inference import FasterWhisperInference
  File "C:\Users\Adminstrator\Desktop\desk\Whisper-WebUI\modules\whisper\faster_whisper_inference.py", line 4, in <module>
    import torch
  File "C:\Users\Adminstrator\Desktop\desk\Whisper-WebUI\venv\lib\site-packages\torch\__init__.py", line 148, in <module>
    raise err
OSError: [WinError 126] The specified module could not be found. Error loading "C:\Users\Adminstrator\Desktop\desk\Whisper-WebUI\venv\lib\site-packages\torch\lib\fbgemm.dll" or one of its dependencies.
"launching the app"

I found this problem's cause is torch.
But I don't know how to solve..
I did reinstalling torch, this project.

**Comment by hactuber** [comment]
fixed, thx

**Comment by sunruichao** [comment]
fixed, thx
