### ISSUE TITLE
코랩 버전이 작동하지 않습니다

### ISSUE THREAD

**Issue by qazs12** [jhj0517/Whisper-WebUI#256]
**Which OS are you using?**
 - OS: Colab
 
 며칠 전까지만 해도 코랩 버전이 됐었는데, 오늘부터 갑자기
 Traceback (most recent call last):
  File "/content/Whisper-WebUI/app.py", line 5, in <module>
    from modules.whisper.whisper_factory import WhisperFactory
  File "/content/Whisper-WebUI/modules/whisper/whisper_factory.py", line 4, in <module>
    from modules.whisper.faster_whisper_inference import FasterWhisperInference
  File "/content/Whisper-WebUI/modules/whisper/faster_whisper_inference.py", line 15, in <module>
    from modules.whisper.whisper_base import WhisperBase
  File "/content/Whisper-WebUI/modules/whisper/whisper_base.py", line 13, in <module>
    from modules.utils.youtube_manager import get_ytdata, get_ytaudio
  File "/content/Whisper-WebUI/modules/utils/youtube_manager.py", line 1, in <module>
    from pytubefix import YouTube
  File "/usr/local/lib/python3.10/dist-packages/pytubefix/__init__.py", line 13, in <module>
    from pytubefix.streams import Stream
  File "/usr/local/lib/python3.10/dist-packages/pytubefix/streams.py", line 20, in <module>
    from pytubefix import extract, request
  File "/usr/local/lib/python3.10/dist-packages/pytubefix/extract.py", line 443
    logger.debug(f'Applying po_token to itag={stream['itag']}')
                                                      ^^^^
SyntaxError: f-string: unmatched '['
이런 오류가 뜨면서 되지 않습니다

해결될 가능성이나 방법같은게 있을까요?

**Comment by jhj0517** [comment]
안녕하세요. `pytubefix`에서 몇 시간 전에 배포된 패키지에서 버그가 있었는데요, (https://github.com/JuanBindez/pytubefix/issues/213)

[새로운 버전](https://colab.research.google.com/github/jhj0517/Whisper-WebUI/blob/master/notebook/whisper-webui.ipynb) 으로 해보시겠어요?

**Comment by qazs12** [comment]
새로운 버전으로 하니까 되네요 감사합니다!

**Comment by JuanBindez** [comment]
안녕하세요 새롭게 수정된 버전 6.15.1을 출시했습니다.

**Comment by abishekmuthian** [comment]
The fix - https://github.com/jhj0517/Whisper-WebUI/issues/256 seems to have commented out and so I'm facing the same issue - `ModuleNotFoundError: No module named 'gradio_i18n'`
