### ISSUE TITLE
pydantic.errors.PydanticSchemaGenerationError: Unable to generate pydantic-core schema for <class starlette.requests.Request>

### ISSUE THREAD

**Issue by megapro17** [jhj0517/Whisper-WebUI#258]
I've just downloaded whisper-webui, installed it from the ground up, and after starting i get this huge error. I didn't change anything

Also I've noticed that models folder is empty

OS: Windows 11
Build: 24H2 (26100)

<details>

![image](https://github.com/user-attachments/assets/0d5a7023-e6b8-4dee-a73b-d7ad6974302e)

</details>

<details>

```
megapro17@megapro17-pc  ~  Desktop  Soft  Huge  Whisper-WebUI-Portable-Windows  Whisper-WebUI  master  git log

commit 8bcf1fbf836ba832efa77bc0b190d982f4ee8234 (HEAD -> master, origin/master, origin/HEAD)
Merge: 4904f1c d8c2d87
Author: jhj0517 <97279763+jhj0517@users.noreply.github.com>
Date:   Thu Sep 5 23:42:10 2024 +0900

    Merge pull request #255 from jhj0517/feature/remember-settings

    Load & cache settings

commit d8c2d8700e2e1175afea06b1eced22778f71ac73
Author: jhj0517 <97279763+jhj0517@users.noreply.github.com>
Date:   Thu Sep 5 16:30:33 2024 +0900

    Fix key

commit bf46b638264b8e35c36afc1c74e49880ea7b1f9e
Author: jhj0517 <97279763+jhj0517@users.noreply.github.com>
Date:   Thu Sep 5 16:12:32 2024 +0900

    Apply path constants

commit 6f6c89b5c1b0be8b99f5e362ffcee43e521c571d
Author: jhj0517 <97279763+jhj0517@users.noreply.github.com>
Date:   Thu Sep 5 01:46:00 2024 +0900

    Apply `add_timestamp` in caching

commit 51a408d411d113b240a76c03018a1c08f7034999
Author: jhj0517 <97279763+jhj0517@users.noreply.github.com>
megapro17@megapro17-pc  ~  Desktop  Soft  Huge  Whisper-WebUI-Portable-Windows  Whisper-WebUI  master 
 git status
On branch master
Your branch is up to date with 'origin/master'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)
        modules/diarize/__pycache__/
        modules/translation/__pycache__/
        modules/utils/__pycache__/
        modules/vad/__pycache__/
        modules/whisper/__pycache__/

nothing added to commit but untracked files present (use "git add" to track)
 megapro17@megapro17-pc  ~  Desktop  Soft  Huge  Whisper-WebUI-Portable-Windows  .\update.bat
Already up to date.
Successfully updated WebUI.
Press any key to continue . . .
 megapro17@megapro17-pc  ~  Desktop  Soft  Huge  Whisper-WebUI-Portable-Windows  .\start-webui.bat
Use "faster-whisper" implementation
Device "cuda" is detected
Running on local URL:  http://127.0.0.1:7861

To create a public link, set `share=True` in `launch()`.
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\megapro17\Desktop\Soft\Huge\Whisper-WebUI-Portable-Windows\Whisper-WebUI\venv\Lib\site-packages\pydantic\type_adapter.py", line 279, in _init_core_attrs
    self._core_schema = _getattr_no_parents(self._type, '__pydantic_core_schema__')
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\megapro17\Desktop\Soft\Huge\Whisper-WebUI-Portable-Windows\Whisper-WebUI\venv\Lib\site-packages\pydantic\type_adapter.py", line 121, in _getattr_no_parents
    raise AttributeError(attribute)
AttributeError: __pydantic_core_schema__

During handling of the above exception, another exception occurred:

<...>

  File "C:\Users\megapro17\Desktop\Soft\Huge\Whisper-WebUI-Portable-Windows\Whisper-WebUI\venv\Lib\site-packages\pydantic\_internal\_generate_schema.py", line 2085, in inner_handler
    schema = self._generate_schema_inner(obj)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\megapro17\Desktop\Soft\Huge\Whisper-WebUI-Portable-Windows\Whisper-WebUI\venv\Lib\site-packages\pydantic\_internal\_generate_schema.py", line 929, in _generate_schema_inner
    return self.match_type(obj)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\megapro17\Desktop\Soft\Huge\Whisper-WebUI-Portable-Windows\Whisper-WebUI\venv\Lib\site-packages\pydantic\_internal\_generate_schema.py", line 1029, in match_type
    return self._match_generic_type(obj, origin)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\megapro17\Desktop\Soft\Huge\Whisper-WebUI-Portable-Windows\Whisper-WebUI\venv\Lib\site-packages\pydantic\_internal\_generate_schema.py", line 1058, in _match_generic_type
    return self._union_schema(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\megapro17\Desktop\Soft\Huge\Whisper-WebUI-Portable-Windows\Whisper-WebUI\venv\Lib\site-packages\pydantic\_internal\_generate_schema.py", line 1378, in _union_schema
    choices.append(self.generate_schema(arg))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\megapro17\Desktop\Soft\Huge\Whisper-WebUI-Portable-Windows\Whisper-WebUI\venv\Lib\site-packages\pydantic\_internal\_generate_schema.py", line 655, in generate_schema
    schema = self._generate_schema_inner(obj)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\megapro17\Desktop\Soft\Huge\Whisper-WebUI-Portable-Windows\Whisper-WebUI\venv\Lib\site-packages\pydantic\_internal\_generate_schema.py", line 929, in _generate_schema_inner
    return self.match_type(obj)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\megapro17\Desktop\Soft\Huge\Whisper-WebUI-Portable-Windows\Whisper-WebUI\venv\Lib\site-packages\pydantic\_internal\_generate_schema.py", line 1038, in match_type
    return self._unknown_type_schema(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\megapro17\Desktop\Soft\Huge\Whisper-WebUI-Portable-Windows\Whisper-WebUI\venv\Lib\site-packages\pydantic\_internal\_generate_schema.py", line 558, in _unknown_type_schema
    raise PydanticSchemaGenerationError(
pydantic.errors.PydanticSchemaGenerationError: Unable to generate pydantic-core schema for <class 'starlette.requests.Request'>. Set `arbitrary_types_allowed=True` in the model_config to ignore this error or implement `__get_pydantic_core_schema__` on your type to fully support it.

If you got this error by calling handler(<some type>) within `__get_pydantic_core_schema__` then you likely need to call `handler.generate_schema(<some type>)` since we do not call `__get_pydantic_core_schema__` on `<some type>` otherwise to avoid infinite recursion.

For further information visit https://errors.pydantic.dev/2.9/u/schema-for-unknown-type
```

</details>

[log.txt](https://github.com/user-attachments/files/16900845/log.txt)

**Comment by tripleS-Dev** [comment]
me too
OS: Windows 11
빌드: 24H2(26100)
others are same

**Comment by danik9711** [comment]
The same
OS: MacOS Sonoma 14.5
Start with docker
Log is same absolutely

**Comment by jhj0517** [comment]
Ah, it seems there's a dependency incompatibility issue with older versions of `gradio` - https://github.com/gradio-app/gradio/issues/9278

@danik9711 @tripleS-Dev @megapro17 
I fixed it in #259, can you check the latest version?

If you hate to reinstall the whole thing, you can just update the `gradio` after activating the venv -
```
# (After activating venv)
pip install -U gradio==4.43.0
```

<details>
    <summary>How to activate the venv?</summary>
    
- On Windows
1. open the terminal in to the Whisper-WebUI path
```
C:\Path\To\WebUI>
```
2. Activate the venv
```
C:\Path\To\WebUI>.\venv\Scripts\activate
```
After activation, you should see (venv) in front of the terminal.
```
(venv) C:\Path\To\WebUI>
```
3. In this state, run
```
pip install -U gradio
```

- On Mac
1. open the terminal in to the Whisper-WebUI path
```
C:\Path\To\WebUI>
```
2. Activate the venv
```
C:\Path\To\WebUI>venv\Scripts\activate
```
After activation, you should see (venv) in front of the terminal.
```
(venv) Path/To/WebUI>source venv/bin/activate 
```
3. In this state, run
```
pip install -U gradio
```
</details>

**Comment by robomana** [comment]
confirmed fixed

**Comment by megapro17** [comment]
`pip install -U gradio`

Thank you, it was fixed

**Comment by AlicanAKCA** [comment]
I hope there is a solution other than upgrading gradio. I have to use gradio 4.38.1.

**Comment by jhj0517** [comment]
@AlicanAKCA You can downgrade `fastapi`
```
pip install -U fastapi==0.112.4
```

**Comment by github0hello** [comment]
thank you

**Comment by miguelgargallo** [comment]
Thanks that saved me
