### ISSUE TITLE
Error transcribing file: tuple index out of range

### ISSUE THREAD

**Issue by 1247862674** [jhj0517/Whisper-WebUI#262]
ubuntu22.04
python3.10.14
Error transcribing file: tuple index out of range
Traceback (most recent call last):
  File "/data/miniconda3/pkgs/whisper-webui/lib/python3.10/site-packages/gradio/queueing.py", line 527, in process_events
    response = await route_utils.call_process_api(
  File "/data/miniconda3/pkgs/whisper-webui/lib/python3.10/site-packages/gradio/route_utils.py", line 270, in call_process_api
    output = await app.get_blocks().process_api(
  File "/data/miniconda3/pkgs/whisper-webui/lib/python3.10/site-packages/gradio/blocks.py", line 1856, in process_api
    data = await self.postprocess_data(fn_index, result["prediction"], state)
  File "/data/miniconda3/pkgs/whisper-webui/lib/python3.10/site-packages/gradio/blocks.py", line 1634, in postprocess_data
    self.validate_outputs(fn_index, predictions)  # type: ignore
  File "/data/miniconda3/pkgs/whisper-webui/lib/python3.10/site-packages/gradio/blocks.py", line 1610, in validate_outputs
    raise ValueError(
ValueError: An event handler (transcribe_file) didn't receive enough output values (needed: 2, received: 1).
Wanted outputs:
    [<gradio.components.textbox.Textbox object at 0x7f1a95567610>, <gradio.templates.Files object at 0x7f1a955677f0>]
Received outputs:
    [None]

How do I need to solve this?

**Comment by jhj0517** [comment]
Not enough information to reproduce the bug,
If this bug is related to older versions of Gradio, it's fixed in #259.

Can you check the latest version of the webui?
Or you can just update the gradio. (after activating venv)
```
pip install -U gradio
```

**Comment by 1247862674** [comment]
> Not enough information to reproduce the bug, If this bug is related to older versions of Gradio, it's fixed in #259.
> 
> Can you check the latest version of the webui? Or you can just update the gradio. (after activating venv)
> 
> ```
> pip install -U gradio
> ```
I'm using a MOV video format, and I couldn't solve it when I tried to upgrade

**Comment by 1247862674** [comment]
! [image] (https://github.com/user-attachments/assets/ef030b29-f9b7-41f2-80a3-0625d22e0c3f)
My version is already up to date

**Comment by jhj0517** [comment]
OK, the requirements.txt is updated, but the actual dependency from your `venv` directory may not be updated. 
You need to update gradio after activating `venv` if you haven't already, 
```
# (After activating venv)
pip install -U gradio==4.43.0
```

<details>
    <summary>How to activate the venv?</summary>
    
1. open the terminal in your web ui path
```
/Path/To/WebUI>
```
2. Activate the venv
```
/Path/To/WebUI>source venv/bin/activate 
```
After activation, you should see (venv) in front of the terminal.
```
(venv) /Path/To/WebUI>
```
3. In this state, run
```
pip install -U gradio
```
</details>


Or you can just remove the `venv` directory and run the install script again.

**Comment by PgvCMCz518** [comment]
Came to similar issuse
m4a file

(venv) root@3e2bff99ed15:/Whisper-WebUI# pip list|grep gra
gradio                   4.43.0


Error transcribing file: max() arg is an empty sequence
Traceback (most recent call last):
  File "/Whisper-WebUI/venv/lib/python3.11/site-packages/gradio/queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Whisper-WebUI/venv/lib/python3.11/site-packages/gradio/route_utils.py", line 321, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Whisper-WebUI/venv/lib/python3.11/site-packages/gradio/blocks.py", line 1945, in process_api
    data = await self.postprocess_data(block_fn, result["prediction"], state)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Whisper-WebUI/venv/lib/python3.11/site-packages/gradio/blocks.py", line 1717, in postprocess_data
    self.validate_outputs(block_fn, predictions)  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Whisper-WebUI/venv/lib/python3.11/site-packages/gradio/blocks.py", line 1691, in validate_outputs
    raise ValueError(
ValueError: An event handler (transcribe_file) didn't receive enough output values (needed: 2, received: 1).
Wanted outputs:
    [<gradio.components.textbox.Textbox object at 0x7ff00f4b8f10>, <gradio.templates.Files object at 0x7ff00d3ae590>]
Received outputs:
    [None]
