### ISSUE TITLE
ubuntu22.04 python3.10.14 I'm using Mic's graphics card.,Recorded the sound.,Didn't set any parameters.,Use the default settings.,There was a problem with clicking on the generated subtitles:missing 1 required positional argument: 'language_detection_segments'  

### ISSUE THREAD

**Issue by 1247862674** [jhj0517/Whisper-WebUI#263]
Error transcribing file: WhisperValues.__init__() missing 1 required positional argument: 'language_detection_segments'
Traceback (most recent call last):
  File "/data/miniconda3/pkgs/whisper-webui/lib/python3.10/site-packages/gradio/queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
  File "/data/miniconda3/pkgs/whisper-webui/lib/python3.10/site-packages/gradio/route_utils.py", line 321, in call_process_api
    output = await app.get_blocks().process_api(
  File "/data/miniconda3/pkgs/whisper-webui/lib/python3.10/site-packages/gradio/blocks.py", line 1945, in process_api
    data = await self.postprocess_data(block_fn, result["prediction"], state)
  File "/data/miniconda3/pkgs/whisper-webui/lib/python3.10/site-packages/gradio/blocks.py", line 1717, in postprocess_data
    self.validate_outputs(block_fn, predictions)  # type: ignore
  File "/data/miniconda3/pkgs/whisper-webui/lib/python3.10/site-packages/gradio/blocks.py", line 1691, in validate_outputs
    raise ValueError(
ValueError: An event handler (transcribe_mic) didn't receive enough output values (needed: 2, received: 1).
Wanted outputs:
    [<gradio.components.textbox.Textbox object at 0x7f3a51a26f20>, <gradio.templates.Files object at 0x7f3a51a26e30>]
Received outputs:
    [None]

**Comment by 1247862674** [comment]
![image](https://github.com/user-attachments/assets/198c2b0e-255e-4bd0-9977-43b8b09669db)

**Comment by jhj0517** [comment]
@1247862674 Thanks for noticing. 
This is fixed #264.

Please feel free to reopen and let me know if you are still having problems!

**Comment by 1247862674** [comment]
Error transcribing file: File object has no read() method, or readable() returned False.
Traceback (most recent call last):
  File "/data/miniconda3/pkgs/whisper-webui/lib/python3.10/site-packages/gradio/queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
  File "/data/miniconda3/pkgs/whisper-webui/lib/python3.10/site-packages/gradio/route_utils.py", line 321, in call_process_api
    output = await app.get_blocks().process_api(
  File "/data/miniconda3/pkgs/whisper-webui/lib/python3.10/site-packages/gradio/blocks.py", line 1945, in process_api
    data = await self.postprocess_data(block_fn, result["prediction"], state)
  File "/data/miniconda3/pkgs/whisper-webui/lib/python3.10/site-packages/gradio/blocks.py", line 1717, in postprocess_data
    self.validate_outputs(block_fn, predictions)  # type: ignore
  File "/data/miniconda3/pkgs/whisper-webui/lib/python3.10/site-packages/gradio/blocks.py", line 1691, in validate_outputs
    raise ValueError(
ValueError: An event handler (transcribe_mic) didn't receive enough output values (needed: 2, received: 1).
Wanted outputs:
    [<gradio.components.textbox.Textbox object at 0x7f217ff90460>, <gradio.templates.Files object at 0x7f217ff903a0>]
Received outputs:
    [None] 
      Now there are other errors

**Comment by 1247862674** [comment]
> @1247862674 Thanks for noticing. Thank you for your interest. This is fixed #264. This is fixed #264.
> 
> Please feel free to reopen and let me know if you are still having problems!

Please open it, it still has other bugs

**Comment by 1247862674** [comment]
Please, what do I need to do to fix this?

**Comment by jhj0517** [comment]
Cannot reproduce the error.

> File object has no read() method, or readable() returned False.

It seems that maybe somehow your environment does not allow to call `faster_whisper.decode_audio()` on your audio file?
Just for information, does this also happen in other tabs (Files or Youtube) or only in the Mic tab?


Until this is fixed, I'd recommend to use Docker.

1. Install Docker desktop - https://www.docker.com/products/docker-desktop/

2. Open the Docker desktop and follow [Running with Docker](https://github.com/jhj0517/Whisper-WebUI?tab=readme-ov-file#running-with-docker) guide.

If you have any questions feel free to ask

**Comment by 1247862674** [comment]
The other tabs are normal

**Comment by 1247862674** [comment]
I found that I had this error when I clicked on the subtitle for the first time after recording, and it was normal to click again after the error message appeared

**Comment by 1247862674** [comment]
OK, I know what's wrong, this one is because the recorded audio is not stored in the local gradio cache directory and the read fails
