### ISSUE TITLE
Diarization failed

### ISSUE THREAD

**Issue by PgvCMCz518** [jhj0517/Whisper-WebUI#265]
Already did huggingface-cli  login and manually download the model is ok.

log :
Failed to diarize. You need huggingface token and agree to their requirements to download the diarization model.
Go to "https://huggingface.co/pyannote/speaker-diarization-3.1" and follow their instructions to download the model.

Error transcribing file: 'NoneType' object is not callable
Traceback (most recent call last):
  File "/home/user1/work/Whisper-WebUI.new/venv/lib/python3.10/site-packages/gradio/queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
  File "/home/user1/work/Whisper-WebUI.new/venv/lib/python3.10/site-packages/gradio/route_utils.py", line 321, in call_process_api
    output = await app.get_blocks().process_api(
  File "/home/user1/work/Whisper-WebUI.new/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1945, in process_api
    data = await self.postprocess_data(block_fn, result["prediction"], state)
  File "/home/user1/work/Whisper-WebUI.new/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1717, in postprocess_data
    self.validate_outputs(block_fn, predictions)  # type: ignore
  File "/home/user1/work/Whisper-WebUI.new/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1691, in validate_outputs
    raise ValueError(
ValueError: An event handler (transcribe_file) didn't receive enough output values (needed: 2, received: 1).
Wanted outputs:
    [<gradio.components.textbox.Textbox object at 0x7fd8cb2b7340>, <gradio.templates.Files object at 0x7fd8cb2b7490>]
Received outputs:
    [None]

Thanks.

**Comment by jhj0517** [comment]
Just to check, did you agree to TOS for both models?

1. https://huggingface.co/pyannote/speaker-diarization-3.1
2. https://huggingface.co/pyannote/segmentation-3.0

[README](https://github.com/jhj0517/Whisper-WebUI?tab=readme-ov-file#feature) says you have to agree for both.

**Comment by PgvCMCz518** [comment]
Yes, I did.

**Comment by jhj0517** [comment]
It seems like you mannually downloaded models to `/.cache/huggingface/hub/` directory, not `Path/WebUI/models/Diarizer` ?

Just entering the huggingface token with read permission would automatically download the models to the right path.

**Comment by PgvCMCz518** [comment]
Entered to the UI and it works now,thaks.

But m4a file failed.


Logs:

Error transcribing file: max() arg is an empty sequence
Traceback (most recent call last):
  File "/Whisper-WebUI/venv/lib/python3.11/site-packages/gradio/queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Whisper-WebUI/venv/lib/python3.11/site-packages/gradio/route_utils.py", line 321, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Whisper-WebUI/venv/lib/python3.11/site-packages/gradio/blocks.py", line 1945, in process_api
    data = await self.postprocess_data(block_fn, result["prediction"], state)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Whisper-WebUI/venv/lib/python3.11/site-packages/gradio/blocks.py", line 1717, in postprocess_data
    self.validate_outputs(block_fn, predictions)  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Whisper-WebUI/venv/lib/python3.11/site-packages/gradio/blocks.py", line 1691, in validate_outputs
    raise ValueError(
ValueError: An event handler (transcribe_file) didn't receive enough output values (needed: 2, received: 1).
Wanted outputs:
    [<gradio.components.textbox.Textbox object at 0x7f912c4544d0>, <gradio.templates.Files object at 0x7f912c41cc10>]
Received outputs:
    [None]

**Comment by PgvCMCz518** [comment]
Entered into the UI and it works now, thanks a lot.
