### ISSUE TITLE
이번 업데이트 이후로 오류뜹니다

### ISSUE THREAD

**Issue by SeongGyu1216** [jhj0517/Whisper-WebUI#273]
Window 11

Traceback (most recent call last):
  File "E:\Whisper-WebUI\app.py", line 10, in <module>
    from modules.whisper.whisper_factory import WhisperFactory
  File "E:\Whisper-WebUI\modules\whisper\whisper_factory.py", line 6, in <module>
    from modules.whisper.faster_whisper_inference import FasterWhisperInference
  File "E:\Whisper-WebUI\modules\whisper\faster_whisper_inference.py", line 16, in <module>
    from modules.whisper.whisper_base import WhisperBase
  File "E:\Whisper-WebUI\modules\whisper\whisper_base.py", line 13, in <module>
    from modules.uvr.music_separator import MusicSeparator
  File "E:\Whisper-WebUI\modules\uvr\music_separator.py", line 11, in <module>
    from uvr.models import MDX, Demucs, VrNetwork, MDXC
ModuleNotFoundError: No module named 'uvr'
"launching the app"
계속하려면 아무 키나 누르십시오 . . .

update를 bat파일로했습니다.

**Comment by jhj0517** [comment]
안녕하세요. 이번 업데이트에는 패키지 몇개가 추가 되었기 때문에 install.bat 을 추가로 실행해 주셔야 합니다.
install.bat 을 실행하신 후 다시 실행해보시겠어요?

**Comment by jhj0517** [comment]
@SeongGyu1216 방금 포크한 ultimatevocalremover_api 에서 `diffq`를 비활성화 했는데요,
다시 `install.bat` 을 실행해보시겠어요?

**Comment by SeongGyu1216** [comment]
이제 정상작동하는 것 같습니다 !감사합니다
