### ISSUE TITLE
onnx_cpp2py_export error

### ISSUE THREAD

**Issue by MasterRuma** [jhj0517/Whisper-WebUI#285]
run ``start-webui.bat``
```Traceback (most recent call last):
  File "D:\AI\Whisper-WebUI\app.py", line 10, in <module>
    from modules.whisper.whisper_factory import WhisperFactory
  File "D:\AI\Whisper-WebUI\modules\whisper\whisper_factory.py", line 6, in <module>
    from modules.whisper.faster_whisper_inference import FasterWhisperInference
  File "D:\AI\Whisper-WebUI\modules\whisper\faster_whisper_inference.py", line 16, in <module>
    from modules.whisper.whisper_base import WhisperBase
  File "D:\AI\Whisper-WebUI\modules\whisper\whisper_base.py", line 13, in <module>
    from modules.uvr.music_separator import MusicSeparator
  File "D:\AI\Whisper-WebUI\modules\uvr\music_separator.py", line 11, in <module>
    from uvr.models import MDX, Demucs, VrNetwork, MDXC
  File "D:\AI\Whisper-WebUI\venv\lib\site-packages\uvr\models.py", line 9, in <module>
    from .models_dir.mdx import mdx_interface as mdx_api
  File "D:\AI\Whisper-WebUI\venv\lib\site-packages\uvr\models_dir\mdx\mdx_interface.py", line 10, in <module>
    from onnx import load
  File "D:\AI\Whisper-WebUI\venv\lib\site-packages\onnx\__init__.py", line 77, in <module>
    from onnx.onnx_cpp2py_export import ONNX_ML
ImportError: DLL load failed while importing onnx_cpp2py_export: DLL 초기화 루틴을 실행할 수 없습니다.
"launching the app"
계속하려면 아무 키나 누르십시오 . . .
```

나의 그래픽 카드 버전 ``nvidia-smi``

```
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 560.94                 Driver Version: 560.94         CUDA Version: 12.6     |
|-----------------------------------------+------------------------+----------------------+
```

venv 안 torch 와 CUDA 버전
```
torch: 2.4.1+cu124
CUDA: 12.4
```

발생 오류 :
install.bat를 실행하고 start-webui.bat를 실행하면 윗 에러가 발생.

**Comment by MasterRuma** [comment]
해결 했습니다.
requirements.txt에 2가지만 추가하면 됩니다

```
onnx==1.13.1
onnxruntime-gpu==1.15.1
```

티켓은 닫도록 하겠습니다.

**Comment by jhj0517** [comment]
Investigating.

Related issues:

- https://github.com/onnx/onnx/issues/6267
- https://github.com/Gourieff/comfyui-reactor-node/issues/384

It seems like this only happens on `python <= 3.9`. Failed to reproduce it on `python 3.11`

[Downgrading onnx](https://github.com/onnx/onnx/issues/6267#issuecomment-2288693895) would solve the problem temporarily.
