### ISSUE TITLE
distil_whisper .en models

### ISSUE THREAD

**Issue by dng-nguyn** [jhj0517/Whisper-WebUI#301]
**Which OS are you using?** Arch Linux
Type: insanely-fast-whisper
The error was raised after trying to transcribe with distil en models:
```sh
Error transcribing file: Cannot specify `task` or `language` for an English-only model. If the model is intended to be multilingual, pass `is_multilingual=True` to generate, or update the generation config.
Traceback (most recent call last):
  File "/root/Whisper-WebUI/venv/lib/python3.12/site-packages/gradio/queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/Whisper-WebUI/venv/lib/python3.12/site-packages/gradio/route_utils.py", line 321, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/Whisper-WebUI/venv/lib/python3.12/site-packages/gradio/blocks.py", line 1945, in process_api
    data = await self.postprocess_data(block_fn, result["prediction"], state)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/Whisper-WebUI/venv/lib/python3.12/site-packages/gradio/blocks.py", line 1717, in postprocess_data
    self.validate_outputs(block_fn, predictions)  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/Whisper-WebUI/venv/lib/python3.12/site-packages/gradio/blocks.py", line 1691, in validate_outputs
    raise ValueError(
ValueError: An event handler (transcribe_file) didn't receive enough output values (needed: 2, received: 1).
Wanted outputs:
    [<gradio.components.textbox.Textbox object at 0x78f9b22ac9b0>, <gradio.templates.Files object at 0x78f8cf30e750>]
Received outputs:
    [None]
    ```

**Comment by dng-nguyn** [comment]
After some additional testing, it seems that all .en models are not usable in insanely-fast-whisper

**Comment by jhj0517** [comment]
Hi @dng-nguyn, I tried to fix it #303, it works now on my test. 
Can you check?

**Comment by dng-nguyn** [comment]
Hello, it works now!
Closing this as resolved.
