### ISSUE TITLE
YouTube doesn't work

### ISSUE THREAD

**Issue by robman501a** [jhj0517/Whisper-WebUI#307]
Every time I enter a YouTube link and hit "Generate subtitle File", I always get an error. I'm even running as admin and completely reinstalled the app from scratch and nothing helped.

I'm using the script with Pinokio.

Windows 11,
32 GB RAM,
Ryzen 5600x
RTX 3060 12GB VRAM
![image](https://github.com/user-attachments/assets/6c897f31-b397-4403-85fe-80ee4c82df28)
![image](https://github.com/user-attachments/assets/06982d27-2738-40ec-a3f8-0dfa2133dfa9)

**Comment by jhj0517** [comment]
Hi. Can you try to update the pytubefix in the Pinoko terminal? 

```
pip install -U pytubefix
```

**Comment by flier268** [comment]
```bash
# pip show pytubefix
Name: pytubefix
Version: 8.12.0
Summary: Python3 library for downloading YouTube Videos.
Home-page: 
Author: 
Author-email: Juan Bindez <juanbindez780@gmail.com>
License: MIT license
Location: /Whisper-WebUI/venv/lib/python3.11/site-packages
Requires: 
Required-by: 
```


```
2025-01-18 16:42:17   warnings.warn(
2025-01-18 18:01:34 Traceback (most recent call last):
2025-01-18 18:01:34   File "/Whisper-WebUI/venv/lib/python3.11/site-packages/pytubefix/__main__.py", line 758, in title
2025-01-18 18:01:34     if 'title' in self.vid_info['videoDetails']:
2025-01-18 18:01:34                   ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
2025-01-18 18:01:34 KeyError: 'videoDetails'
2025-01-18 18:01:34 
2025-01-18 18:01:34 During handling of the above exception, another exception occurred:
2025-01-18 18:01:34 
2025-01-18 18:01:34 Traceback (most recent call last):
2025-01-18 18:01:34   File "/Whisper-WebUI/venv/lib/python3.11/site-packages/gradio/queueing.py", line 625, in process_events
2025-01-18 18:01:34     response = await route_utils.call_process_api(
2025-01-18 18:01:34                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-01-18 18:01:34   File "/Whisper-WebUI/venv/lib/python3.11/site-packages/gradio/route_utils.py", line 322, in call_process_api
2025-01-18 18:01:34     output = await app.get_blocks().process_api(
2025-01-18 18:01:34              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-01-18 18:01:34   File "/Whisper-WebUI/venv/lib/python3.11/site-packages/gradio/blocks.py", line 2042, in process_api
2025-01-18 18:01:34     result = await self.call_function(
2025-01-18 18:01:34              ^^^^^^^^^^^^^^^^^^^^^^^^^
2025-01-18 18:01:34   File "/Whisper-WebUI/venv/lib/python3.11/site-packages/gradio/blocks.py", line 1589, in call_function
2025-01-18 18:01:34     prediction = await anyio.to_thread.run_sync(  # type: ignore
2025-01-18 18:01:34                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-01-18 18:01:34   File "/Whisper-WebUI/venv/lib/python3.11/site-packages/anyio/to_thread.py", line 56, in run_sync
2025-01-18 18:01:34     return await get_async_backend().run_sync_in_worker_thread(
2025-01-18 18:01:34            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-01-18 18:01:34   File "/Whisper-WebUI/venv/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 2461, in run_sync_in_worker_thread
2025-01-18 18:01:34     return await future
2025-01-18 18:01:34            ^^^^^^^^^^^^
2025-01-18 18:01:34   File "/Whisper-WebUI/venv/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 962, in run
2025-01-18 18:01:34     result = context.run(func, *args)
2025-01-18 18:01:34              ^^^^^^^^^^^^^^^^^^^^^^^^
2025-01-18 18:01:34   File "/Whisper-WebUI/venv/lib/python3.11/site-packages/gradio/utils.py", line 883, in wrapper
2025-01-18 18:01:34     response = f(*args, **kwargs)
2025-01-18 18:01:34                ^^^^^^^^^^^^^^^^^^
2025-01-18 18:01:34   File "/Whisper-WebUI/modules/utils/youtube_manager.py", line 12, in get_ytmetas
2025-01-18 18:01:34     return yt.thumbnail_url, yt.title, yt.description
2025-01-18 18:01:34                              ^^^^^^^^
2025-01-18 18:01:34   File "/Whisper-WebUI/venv/lib/python3.11/site-packages/pytubefix/__main__.py", line 794, in title
2025-01-18 18:01:34     self.check_availability()
2025-01-18 18:01:34   File "/Whisper-WebUI/venv/lib/python3.11/site-packages/pytubefix/__main__.py", line 396, in check_availability
2025-01-18 18:01:34     raise exceptions.BotDetection(video_id=self.video_id)
2025-01-18 18:01:34 pytubefix.exceptions.BotDetection: nOy8KZK4kCA This request was detected as a bot. Use `use_po_token=True` or switch to WEB client to view. See more details at https://github.com/JuanBindez/pytubefix/pull/209
2025-01-18 18:02:10 Traceback (most recent call last):
2025-01-18 18:02:10   File "/Whisper-WebUI/venv/lib/python3.11/site-packages/pytubefix/__main__.py", line 758, in title
2025-01-18 18:02:10     if 'title' in self.vid_info['videoDetails']:
2025-01-18 18:02:10                   ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
2025-01-18 18:02:10 KeyError: 'videoDetails'
2025-01-18 18:02:10 
2025-01-18 18:02:10 During handling of the above exception, another exception occurred:
2025-01-18 18:02:10 
2025-01-18 18:02:10 Traceback (most recent call last):
2025-01-18 18:02:10   File "/Whisper-WebUI/venv/lib/python3.11/site-packages/gradio/queueing.py", line 625, in process_events
2025-01-18 18:02:10     response = await route_utils.call_process_api(
2025-01-18 18:02:10                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-01-18 18:02:10   File "/Whisper-WebUI/venv/lib/python3.11/site-packages/gradio/route_utils.py", line 322, in call_process_api
2025-01-18 18:02:10     output = await app.get_blocks().process_api(
2025-01-18 18:02:10              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-01-18 18:02:10   File "/Whisper-WebUI/venv/lib/python3.11/site-packages/gradio/blocks.py", line 2042, in process_api
2025-01-18 18:02:10     result = await self.call_function(
2025-01-18 18:02:10              ^^^^^^^^^^^^^^^^^^^^^^^^^
2025-01-18 18:02:10   File "/Whisper-WebUI/venv/lib/python3.11/site-packages/gradio/blocks.py", line 1589, in call_function
2025-01-18 18:02:10     prediction = await anyio.to_thread.run_sync(  # type: ignore
2025-01-18 18:02:10                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-01-18 18:02:10   File "/Whisper-WebUI/venv/lib/python3.11/site-packages/anyio/to_thread.py", line 56, in run_sync
2025-01-18 18:02:10     return await get_async_backend().run_sync_in_worker_thread(
2025-01-18 18:02:10            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-01-18 18:02:10   File "/Whisper-WebUI/venv/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 2461, in run_sync_in_worker_thread
2025-01-18 18:02:10     return await future
2025-01-18 18:02:10            ^^^^^^^^^^^^
2025-01-18 18:02:10   File "/Whisper-WebUI/venv/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 962, in run
2025-01-18 18:02:10     result = context.run(func, *args)
2025-01-18 18:02:10              ^^^^^^^^^^^^^^^^^^^^^^^^
2025-01-18 18:02:10   File "/Whisper-WebUI/venv/lib/python3.11/site-packages/gradio/utils.py", line 883, in wrapper
2025-01-18 18:02:10     response = f(*args, **kwargs)
2025-01-18 18:02:10                ^^^^^^^^^^^^^^^^^^
2025-01-18 18:02:10   File "/Whisper-WebUI/modules/utils/youtube_manager.py", line 12, in get_ytmetas
2025-01-18 18:02:10     return yt.thumbnail_url, yt.title, yt.description
2025-01-18 18:02:10                              ^^^^^^^^
2025-01-18 18:02:10   File "/Whisper-WebUI/venv/lib/python3.11/site-packages/pytubefix/__main__.py", line 794, in title
2025-01-18 18:02:10     self.check_availability()
2025-01-18 18:02:10   File "/Whisper-WebUI/venv/lib/python3.11/site-packages/pytubefix/__main__.py", line 396, in check_availability
2025-01-18 18:02:10     raise exceptions.BotDetection(video_id=self.video_id)
2025-01-18 18:02:10 pytubefix.exceptions.BotDetection: nOy8KZK4kCA This request was detected as a bot. Use `use_po_token=True` or switch to WEB client to view. See more details at https://github.com/JuanBindez/pytubefix/pull/209
2025-01-18 18:22:29 Traceback (most recent call last):
2025-01-18 18:22:29   File "/Whisper-WebUI/venv/lib/python3.11/site-packages/pytubefix/__main__.py", line 758, in title
2025-01-18 18:22:29     if 'title' in self.vid_info['videoDetails']:
2025-01-18 18:22:29                   ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
2025-01-18 18:22:29 KeyError: 'videoDetails'
2025-01-18 18:22:29 
2025-01-18 18:22:29 During handling of the above exception, another exception occurred:
2025-01-18 18:22:29 
2025-01-18 18:22:29 Traceback (most recent call last):
2025-01-18 18:22:29   File "/Whisper-WebUI/venv/lib/python3.11/site-packages/gradio/queueing.py", line 625, in process_events
2025-01-18 18:22:29     response = await route_utils.call_process_api(
2025-01-18 18:22:29                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-01-18 18:22:29   File "/Whisper-WebUI/venv/lib/python3.11/site-packages/gradio/route_utils.py", line 322, in call_process_api
2025-01-18 18:22:29     output = await app.get_blocks().process_api(
2025-01-18 18:22:29              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-01-18 18:22:29   File "/Whisper-WebUI/venv/lib/python3.11/site-packages/gradio/blocks.py", line 2042, in process_api
2025-01-18 18:22:29     result = await self.call_function(
2025-01-18 18:22:29              ^^^^^^^^^^^^^^^^^^^^^^^^^
2025-01-18 18:22:29   File "/Whisper-WebUI/venv/lib/python3.11/site-packages/gradio/blocks.py", line 1589, in call_function
2025-01-18 18:22:29     prediction = await anyio.to_thread.run_sync(  # type: ignore
2025-01-18 18:22:29                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-01-18 18:22:29   File "/Whisper-WebUI/venv/lib/python3.11/site-packages/anyio/to_thread.py", line 56, in run_sync
2025-01-18 18:22:29     return await get_async_backend().run_sync_in_worker_thread(
2025-01-18 18:22:29            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-01-18 18:22:29   File "/Whisper-WebUI/venv/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 2461, in run_sync_in_worker_thread
2025-01-18 18:22:29     return await future
2025-01-18 18:22:29            ^^^^^^^^^^^^
2025-01-18 18:22:29   File "/Whisper-WebUI/venv/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 962, in run
2025-01-18 18:22:29     result = context.run(func, *args)
2025-01-18 18:22:29              ^^^^^^^^^^^^^^^^^^^^^^^^
2025-01-18 18:22:29   File "/Whisper-WebUI/venv/lib/python3.11/site-packages/gradio/utils.py", line 883, in wrapper
2025-01-18 18:22:29     response = f(*args, **kwargs)
2025-01-18 18:22:29                ^^^^^^^^^^^^^^^^^^
2025-01-18 18:22:29   File "/Whisper-WebUI/modules/utils/youtube_manager.py", line 12, in get_ytmetas
2025-01-18 18:22:29     return yt.thumbnail_url, yt.title, yt.description
2025-01-18 18:22:29                              ^^^^^^^^
2025-01-18 18:22:29   File "/Whisper-WebUI/venv/lib/python3.11/site-packages/pytubefix/__main__.py", line 794, in title
2025-01-18 18:22:29     self.check_availability()
2025-01-18 18:22:29   File "/Whisper-WebUI/venv/lib/python3.11/site-packages/pytubefix/__main__.py", line 396, in check_availability
2025-01-18 18:22:29     raise exceptions.BotDetection(video_id=self.video_id)
2025-01-18 18:22:29 pytubefix.exceptions.BotDetection: nOy8KZK4kCA This request was detected as a bot. Use `use_po_token=True` or switch to WEB client to view. See more details at https://github.com/JuanBindez/pytubefix/pull/209
2025-01-18 20:04:11 INFO:faster_whisper:Processing audio with duration 00:37.675
2025-01-18 20:04:16 INFO:faster_whisper:Detected language 'zh' with probability 0.94
2025-01-18 20:04:36 /Whisper-WebUI/venv/lib/python3.11/site-packages/torch/cuda/memory.py:365: FutureWarning: torch.cuda.reset_max_memory_allocated now calls torch.cuda.reset_peak_memory_stats, which resets /all/ peak memory stats.
2025-01-18 20:04:36   warnings.warn(
2025-01-18 20:17:02 INFO:faster_whisper:Processing audio with duration 10:41.968
2025-01-18 20:17:06 INFO:faster_whisper:Detected language 'zh' with probability 1.00
2025-01-18 20:17:22 sh: 1: start: not found
```

**Comment by jhj0517** [comment]
I just reproduced the same. This happens occasionally for pytube because it affects a lot whenever the API spec is changed by youtube, and it's understandable.

pytube does not work as well with the bug now - https://github.com/pytube/pytube/issues/2119

Until pytubefix fixes this bug, it is recommended to download the youtube video and feed it as a file.

**Comment by guigui0246** [comment]
I got the same error but if I remove the yt.title from my code I get a 403 Forbidden
If that can help fix it faster:
```
Traceback (most recent call last):
  File "C:\Users\guigui0246-EPITECH\OneDrive\curse\non_stop.py", line 79, in <module>
    download(url, ".")
    ~~~~~~~~^^^^^^^^^^
  File "C:\Users\guigui0246-EPITECH\OneDrive\curse\non_stop.py", line 36, in download
    audio_stream = yt.streams.filter(only_audio=True).first()  # type: ignore
                   ^^^^^^^^^^
  File "C:\Users\guigui0246-EPITECH\AppData\Local\Programs\Python\Python313\Lib\site-packages\pytube\__main__.py", line 296, in streams
    return StreamQuery(self.fmt_streams)
                       ^^^^^^^^^^^^^^^^
  File "C:\Users\guigui0246-EPITECH\AppData\Local\Programs\Python\Python313\Lib\site-packages\pytube\__main__.py", line 176, in fmt_streams
    stream_manifest = extract.apply_descrambler(self.streaming_data)
                                                ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\guigui0246-EPITECH\AppData\Local\Programs\Python\Python313\Lib\site-packages\pytube\__main__.py", line 160, in streaming_data
    self.bypass_age_gate()
    ~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\guigui0246-EPITECH\AppData\Local\Programs\Python\Python313\Lib\site-packages\pytube\__main__.py", line 257, in bypass_age_gate
    innertube_response = innertube.player(self.video_id)
  File "C:\Users\guigui0246-EPITECH\AppData\Local\Programs\Python\Python313\Lib\site-packages\pytube\innertube.py", line 448, in player
    return self._call_api(endpoint, query, self.base_data)
           ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\guigui0246-EPITECH\AppData\Local\Programs\Python\Python313\Lib\site-packages\pytube\innertube.py", line 390, in _call_api
    response = request._execute_request(
        endpoint_url,
    ...<2 lines>...
        data=data
    )
  File "C:\Users\guigui0246-EPITECH\AppData\Local\Programs\Python\Python313\Lib\site-packages\pytube\request.py", line 37, in _execute_request
    return urlopen(request, timeout=timeout)  # nosec
  File "C:\Users\guigui0246-EPITECH\AppData\Local\Programs\Python\Python313\Lib\urllib\request.py", line 189, in urlopen
    return opener.open(url, data, timeout)
           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\guigui0246-EPITECH\AppData\Local\Programs\Python\Python313\Lib\urllib\request.py", line 495, in open
    response = meth(req, response)
  File "C:\Users\guigui0246-EPITECH\AppData\Local\Programs\Python\Python313\Lib\urllib\request.py", line 604, in http_response
    response = self.parent.error(
        'http', request, response, code, msg, hdrs)
  File "C:\Users\guigui0246-EPITECH\AppData\Local\Programs\Python\Python313\Lib\urllib\request.py", line 533, in error
    return self._call_chain(*args)
           ~~~~~~~~~~~~~~~~^^^^^^^
  File "C:\Users\guigui0246-EPITECH\AppData\Local\Programs\Python\Python313\Lib\urllib\request.py", line 466, in _call_chain
    result = func(*args)
  File "C:\Users\guigui0246-EPITECH\AppData\Local\Programs\Python\Python313\Lib\urllib\request.py", line 613, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
```

**Comment by jhj0517** [comment]
I couldn't reproduce it anymore, `pytubefix` fixed a bug.
Try to update `pytubefix` with
```
pip install -U pytubefix
```

Then it should work.

Close since this is duplicated with #254
