### ISSUE TITLE
Invalid file type error when trying to upload subtitles for translation

### ISSUE THREAD

**Issue by OneSteelTank** [jhj0517/Whisper-WebUI#335]
**Which OS are you using?**
 - OS: Windows 10

Hi, I'm trying to translate the subtitles I generate with the WebUI but whenever I try to start it I get the error "Invalid file type. Please upload a file that is one of these formats: ['.vtt', '.srt']"" even though my files are in SRT format. This is the full error my log shows: 

```
Traceback (most recent call last):
  File "C:\Users\onest\Downloads\Whisper-WebUI-Portable-Windows\Whisper-WebUI\venv\Lib\site-packages\gradio\queueing.py", line 622, in process_events
    response = await route_utils.call_process_api(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\onest\Downloads\Whisper-WebUI-Portable-Windows\Whisper-WebUI\venv\Lib\site-packages\gradio\route_utils.py", line 323, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\onest\Downloads\Whisper-WebUI-Portable-Windows\Whisper-WebUI\venv\Lib\site-packages\gradio\blocks.py", line 2012, in process_api
    inputs = await self.preprocess_data(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\onest\Downloads\Whisper-WebUI-Portable-Windows\Whisper-WebUI\venv\Lib\site-packages\gradio\blocks.py", line 1711, in preprocess_data
    processed_input.append(block.preprocess(inputs_cached))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\onest\Downloads\Whisper-WebUI-Portable-Windows\Whisper-WebUI\venv\Lib\site-packages\gradio\components\file.py", line 165, in preprocess
    return [self._process_single_file(f) for f in payload]  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\onest\Downloads\Whisper-WebUI-Portable-Windows\Whisper-WebUI\venv\Lib\site-packages\gradio\components\file.py", line 165, in <listcomp>
    return [self._process_single_file(f) for f in payload]  # type: ignore
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\onest\Downloads\Whisper-WebUI-Portable-Windows\Whisper-WebUI\venv\Lib\site-packages\gradio\components\file.py", line 132, in _process_single_file
    raise Error(
gradio.exceptions.Error: "Invalid file type. Please upload a file that is one of these formats: ['.vtt', '.srt']"
```

**Comment by jhj0517** [comment]
Hi @OneSteelTank . Thanks for reporting.

Something is buggy with gradio 5, so I just removed the problematic attribute in #336. 

The new version should work fine. Please let me know if the problem persists.

**Comment by OneSteelTank** [comment]
Worked perfectly after running the update script. Thank you :)
