### ISSUE TITLE
i18n error

### ISSUE THREAD

**Issue by mark-wd** [jhj0517/Whisper-WebUI#356]
Win11, local instance, latest version as of 28 Oct 2024.

I was getting the error below. Did a full reinstall and was still getting it. Console:

`Use "faster-whisper" implementation
Device "cuda" is detected
Traceback (most recent call last):
  File "H:\Whisper-WebUI\app.py", line 483, in <module>
    app.launch()
  File "H:\Whisper-WebUI\app.py", line 232, in launch
    with self.i18n:
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\contextlib.py", line 142, in __exit__
    next(self.gen)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio_i18n\i18n.py", line 330, in Translate
    translation_dict = yaml.safe_load(f)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\yaml\__init__.py", line 125, in safe_load
    return load(stream, SafeLoader)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\yaml\__init__.py", line 79, in load
    loader = Loader(stream)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\yaml\loader.py", line 34, in __init__
    Reader.__init__(self, stream)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\yaml\reader.py", line 85, in __init__
    self.determine_encoding()
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\yaml\reader.py", line 124, in determine_encoding
    self.update_raw()
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\yaml\reader.py", line 178, in update_raw
    data = self.stream.read(size)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 2456: character maps to <undefined>
"launching the app"
Press any key to continue . `

Following the traceback, I went to my "AppData\Local\Programs\Python\Python310\Lib\site-packages\gradio_i18n" and found "i18n.py". I changed line 326 from "with open(translation, "r") as f:" to "with open(translation, "r", encoding="utf-8") as f:" and now the UI runs just fine.

You should account for this situation so that less technical users with certain locale settings don't run into this issue.

**Comment by jhj0517** [comment]
Hi. I thought I covered this in [jhj0517/gradio-i18n](https://github.com/jhj0517/gradio-i18n/tree/fix/encoding-error) and this shouldn't happen anymore.

> "with open(translation, "r") 

This line should be `with open(translation, "r", encoding=find_encoding(translation))` if my patched version is installed properly.

Just for information, did you install the package manually via
```
pip install gradio-i18
```
Or did you install the packages with
```
pip install -r requirements.txt
```
?

**Comment by mark-wd** [comment]
I just ran "install.bat".

**Comment by mark-wd** [comment]
Well, first I updated after not having updated in a month via the updater bat. Then it broke. Then full uninstall and reinstall via the installer bat.

**Comment by jhj0517** [comment]
Well anyway, if you ran install.bat it should not have happened.
I hope https://github.com/hoveychen/gradio-i18n/pull/2 is merged and fixed in the official package.

**Comment by jhj0517** [comment]
Closed as the official package has been updated!
