### ISSUE TITLE
Error in Language Selection

### ISSUE THREAD

**Issue by borahanarslan** [jhj0517/Whisper-WebUI#367]
![image](https://github.com/user-attachments/assets/c84c799a-fde1-4d07-a3b8-072f4fbe8737)

As shown in the screenshot, if I select a language other than Automatic Detection, it results in an error. The error codes are as follows

To create a public link, set `share=True` in `launch()`.
Error transcribing file: 'TranscriptionPipelineParams' object has no attribute 'lang'
D:\Whis\Whisper-WebUI\.venv\lib\site-packages\torch\cuda\memory.py:365: FutureWarning: torch.cuda.reset_max_memory_allocated now calls torch.cuda.reset_peak_memory_stats, which resets /all/ peak memory stats.
  warnings.warn(
Traceback (most recent call last):
  File "D:\Whis\Whisper-WebUI\.venv\lib\site-packages\gradio\queueing.py", line 624, in process_events
    response = await route_utils.call_process_api(
  File "D:\Whis\Whisper-WebUI\.venv\lib\site-packages\gradio\route_utils.py", line 323, in call_process_api
    output = await app.get_blocks().process_api(
  File "D:\Whis\Whisper-WebUI\.venv\lib\site-packages\gradio\blocks.py", line 2018, in process_api
    result = await self.call_function(
  File "D:\Whis\Whisper-WebUI\.venv\lib\site-packages\gradio\blocks.py", line 1567, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
  File "D:\Whis\Whisper-WebUI\.venv\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "D:\Whis\Whisper-WebUI\.venv\lib\site-packages\anyio\_backends\_asyncio.py", line 2441, in run_sync_in_worker_thread
    return await future
  File "D:\Whis\Whisper-WebUI\.venv\lib\site-packages\anyio\_backends\_asyncio.py", line 943, in run
    result = context.run(func, *args)
  File "D:\Whis\Whisper-WebUI\.venv\lib\site-packages\gradio\utils.py", line 846, in wrapper
    response = f(*args, **kwargs)
  File "d:\Whis\Whisper-WebUI\modules\whisper\base_transcription_pipeline.py", line 224, in transcribe_file
    transcribed_segments, time_for_task = self.run(
  File "d:\Whis\Whisper-WebUI\modules\whisper\base_transcription_pipeline.py", line 104, in run
    params = self.validate_gradio_values(params)
  File "d:\Whis\Whisper-WebUI\modules\whisper\base_transcription_pipeline.py", line 495, in validate_gradio_values
    params.whisper.lang = language_code_dict[params.lang]
  File "D:\Whis\Whisper-WebUI\.venv\lib\site-packages\pydantic\main.py", line 856, in __getattr__
    raise AttributeError(f'{type(self).__name__!r} object has no attribute {item!r}')
AttributeError: 'TranscriptionPipelineParams' object has no attribute 'lang'

**Comment by borahanarslan** [comment]
I made 3 changes. I created a language.py file under the Utils folder. I selected the languages ​​in app.py from this file. I also made changes to the base_transcription_pipeline.py file. The error is gone. If you want, you can review and add the necessary changes. 
I committed

**Comment by jhj0517** [comment]
Thanks for pointing this out!
Ah, there was a mistake. Fixed in #372!

Please feel free to reopen.
