### ISSUE TITLE
colab error at the "Run" operation

### ISSUE THREAD

**Issue by joonseo0505** [jhj0517/Whisper-WebUI#392]
**Which OS are you using?**
 - OS: Colab

Im getting following error at Run operation how should i deal with it?

Traceback (most recent call last):
  File "/content/Whisper-WebUI/app.py", line 11, in <module>
    from modules.whisper.whisper_factory import WhisperFactory
  File "/content/Whisper-WebUI/modules/whisper/whisper_factory.py", line 6, in <module>
    from modules.whisper.faster_whisper_inference import FasterWhisperInference
  File "/content/Whisper-WebUI/modules/whisper/faster_whisper_inference.py", line 16, in <module>
    from modules.whisper.base_transcription_pipeline import BaseTranscriptionPipeline
  File "/content/Whisper-WebUI/modules/whisper/base_transcription_pipeline.py", line 12, in <module>
    from modules.uvr.music_separator import MusicSeparator
  File "/content/Whisper-WebUI/modules/uvr/music_separator.py", line 11, in <module>
    from uvr.models import MDX, Demucs, VrNetwork, MDXC
  File "/usr/local/lib/python3.10/dist-packages/uvr/models.py", line 9, in <module>
    from .models_dir.mdx import mdx_interface as mdx_api
  File "/usr/local/lib/python3.10/dist-packages/uvr/models_dir/mdx/mdx_interface.py", line 4, in <module>
    from . import mdxnet as MdxnetSet
  File "/usr/local/lib/python3.10/dist-packages/uvr/models_dir/mdx/mdxnet.py", line 4, in <module>
    from pytorch_lightning import LightningModule
  File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/__init__.py", line 27, in <module>
    from pytorch_lightning.callbacks import Callback  # noqa: E402
  File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/callbacks/__init__.py", line 14, in <module>
    from pytorch_lightning.callbacks.batch_size_finder import BatchSizeFinder
  File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/callbacks/batch_size_finder.py", line 26, in <module>
    from pytorch_lightning.callbacks.callback import Callback
  File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/callbacks/callback.py", line 22, in <module>
    from pytorch_lightning.utilities.types import STEP_OUTPUT
  File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/utilities/types.py", line 42, in <module>
    from torchmetrics import Metric
  File "/usr/local/lib/python3.10/dist-packages/torchmetrics/__init__.py", line 37, in <module>
    from torchmetrics import functional  # noqa: E402
  File "/usr/local/lib/python3.10/dist-packages/torchmetrics/functional/__init__.py", line 125, in <module>
    from torchmetrics.functional.text._deprecated import _bleu_score as bleu_score
  File "/usr/local/lib/python3.10/dist-packages/torchmetrics/functional/text/__init__.py", line 50, in <module>
    from torchmetrics.functional.text.bert import bert_score
  File "/usr/local/lib/python3.10/dist-packages/torchmetrics/functional/text/bert.py", line 56, in <module>
    from transformers import AutoModel, AutoTokenizer
  File "/usr/local/lib/python3.10/dist-packages/transformers/__init__.py", line 26, in <module>
    from . import dependency_versions_check
  File "/usr/local/lib/python3.10/dist-packages/transformers/dependency_versions_check.py", line 57, in <module>
    require_version_core(deps[pkg])
  File "/usr/local/lib/python3.10/dist-packages/transformers/utils/versions.py", line 117, in require_version_core
    return require_version(requirement, hint)
  File "/usr/local/lib/python3.10/dist-packages/transformers/utils/versions.py", line 111, in require_version
    _compare_versions(op, got_ver, want_ver, requirement, pkg, hint)
  File "/usr/local/lib/python3.10/dist-packages/transformers/utils/versions.py", line 44, in _compare_versions
    raise ImportError(
ImportError: tokenizers>=0.20,<0.21 is required for a normal functioning of this module, but found tokenizers==0.19.1.
Try: `pip install transformers -U` or `pip install -e '.[dev]'` if you're working with git main

**Comment by jhj0517** [comment]
Hi, thanks for reporting this.
I don't know how long this has been happening, but it was fixed in #393.

- https://colab.research.google.com/github/jhj0517/Whisper-WebUI/blob/master/notebook/whisper-webui.ipynb

Feel free to reopen if you are still experiencing the problem!
