### ISSUE TITLE
Error when Processing audio/video file duration 1 hours+

### ISSUE THREAD

**Issue by YKefasu** [jhj0517/Whisper-WebUI#394]
**Which OS are you using?**
 - OS: Windows

Always get Error Connection errored out. when processing audio or video files duration that longer than 1 hours

**Comment by jhj0517** [comment]
Hi. Can you paste the full stack trace when it happens?

**Comment by YKefasu** [comment]
```
Use "faster-whisper" implementation
Device "cuda" is detected
* Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.


(env) (base) E:\Pinokio\api\whisper-webui.git\app>
```

https://github.com/user-attachments/assets/fe8d368c-0884-470f-be81-d59e991af5e5

**Comment by jhj0517** [comment]
@YKefasu Can you click the "Terminal" tab after that? I need the information in the terminal, it may display some error messages about it.

**Comment by YKefasu** [comment]
Reset and re-install it again. The error still happened....
![image](https://github.com/user-attachments/assets/3d78d3fa-9101-4343-bb04-559cbd3b7a00)

**Comment by jhj0517** [comment]
I just tried to reproduce it with a 5 hour sample : 
https://www.youtube.com/watch?v=agBuBFbGZAQ&ab_channel=MrBean

But failed, worked fine for me. If someone could provide more detailed information / stack trace about this, I'll look into it more.

Personally, I suspect this is a memory related error, as it seems likely to happen when chunking hours of audio.

**Comment by YKefasu** [comment]
@jhj0517 

```
During handling of the above exception, another exception occurred:
Use "whisper" implementation
Device "cuda" is detected
* Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.

E:\Pinokio\api\whisper-webui.git\app\env\lib\site-packages\whisper\__init__.py:150: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  checkpoint = torch.load(fp, map_location=device)
 28%|██████████████▎                                     | 104370/379212 [01:56<05:07, 892.86frames/s]
Error transcribing file: CUDA error: misaligned address
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
Traceback (most recent call last):
  File "E:\Pinokio\api\whisper-webui.git\app\modules\whisper\base_transcription_pipeline.py", line 228, in transcribe_file
    transcribed_segments, time_for_task = self.run(
  File "E:\Pinokio\api\whisper-webui.git\app\modules\whisper\base_transcription_pipeline.py", line 151, in run
    result, elapsed_time = self.transcribe(
  File "E:\Pinokio\api\whisper-webui.git\app\modules\whisper\whisper_Inference.py", line 62, in transcribe
    result = self.model.transcribe(audio=audio,
  File "E:\Pinokio\api\whisper-webui.git\app\env\lib\site-packages\whisper\transcribe.py", line 284, in transcribe
    result: DecodingResult = decode_with_fallback(mel_segment)
  File "E:\Pinokio\api\whisper-webui.git\app\env\lib\site-packages\whisper\transcribe.py", line 196, in decode_with_fallback
    decode_result = model.decode(segment, options)
  File "E:\Pinokio\api\whisper-webui.git\app\env\lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "E:\Pinokio\api\whisper-webui.git\app\env\lib\site-packages\whisper\decoding.py", line 824, in decode
    result = DecodingTask(model, options).run(mel)
  File "E:\Pinokio\api\whisper-webui.git\app\env\lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "E:\Pinokio\api\whisper-webui.git\app\env\lib\site-packages\whisper\decoding.py", line 734, in run
    tokens = tokens.repeat_interleave(self.n_group, dim=0).to(audio_features.device)
RuntimeError: CUDA error: misaligned address
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Pinokio\api\whisper-webui.git\app\env\lib\site-packages\gradio\queueing.py", line 624, in process_events
    response = await route_utils.call_process_api(
  File "E:\Pinokio\api\whisper-webui.git\app\env\lib\site-packages\gradio\route_utils.py", line 323, in call_process_api
    output = await app.get_blocks().process_api(
  File "E:\Pinokio\api\whisper-webui.git\app\env\lib\site-packages\gradio\blocks.py", line 2015, in process_api
    result = await self.call_function(
  File "E:\Pinokio\api\whisper-webui.git\app\env\lib\site-packages\gradio\blocks.py", line 1562, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
  File "E:\Pinokio\api\whisper-webui.git\app\env\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "E:\Pinokio\api\whisper-webui.git\app\env\lib\site-packages\anyio\_backends\_asyncio.py", line 2441, in run_sync_in_worker_thread
    return await future
  File "E:\Pinokio\api\whisper-webui.git\app\env\lib\site-packages\anyio\_backends\_asyncio.py", line 943, in run
    result = context.run(func, *args)
  File "E:\Pinokio\api\whisper-webui.git\app\env\lib\site-packages\gradio\utils.py", line 865, in wrapper
    response = f(*args, **kwargs)
  File "E:\Pinokio\api\whisper-webui.git\app\modules\whisper\base_transcription_pipeline.py", line 264, in transcribe_file
    self.release_cuda_memory()
  File "E:\Pinokio\api\whisper-webui.git\app\modules\whisper\base_transcription_pipeline.py", line 477, in release_cuda_memory
    torch.cuda.empty_cache()
  File "E:\Pinokio\api\whisper-webui.git\app\env\lib\site-packages\torch\cuda\memory.py", line 192, in empty_cache
    torch._C._cuda_emptyCache()
RuntimeError: CUDA error: misaligned address
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

```

**Comment by YKefasu** [comment]
Working Smoothly after Unistalling the MSI Afterburner and its Riva Tool as mentioned on:
https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/9954#issuecomment-1646832369
![image](https://github.com/user-attachments/assets/a7cfab5b-7221-468e-920c-b593ee969d5b)

**Comment by YKefasu** [comment]
Sorry for bothering you @jhj0517

**Comment by jhj0517** [comment]
@YKefasu No problem at all. Feel free to raise and reopen the issue if you have any problems.
