### ISSUE TITLE
[Speaker diarization] AtributeError: module 'numpy' has no attribute 'NAN'

### ISSUE THREAD

**Issue by xezpeleta** [jhj0517/Whisper-WebUI#403]
The following error happens when I try to transcribe any file, no matter if it's a uploaded file or a downloaded youtube content.

**Which OS are you using?**
 - OS: Ubuntu Linux 20.04
 - Docker 26.1.4

Full error trace:

```
app-1  | INFO:speechbrain.utils.quirks:Applied quirks (see `speechbrain.utils.quirks`): [allow_tf32, disable_jit_profiling]
app-1  | INFO:speechbrain.utils.quirks:Excluded quirks specified by the `SB_DISABLE_QUIRKS` environment (comma-separated list): []
app-1  | /Whisper-WebUI/venv/lib/python3.11/site-packages/pyannote/audio/utils/reproducibility.py:74: ReproducibilityWarning: TensorFloat-32 (TF32) has been disabled as it might lead to reproducibility issues and lower accuracy.
app-1  | It can be re-enabled by calling
app-1  |    >>> import torch
app-1  |    >>> torch.backends.cuda.matmul.allow_tf32 = True
app-1  |    >>> torch.backends.cudnn.allow_tf32 = True
app-1  | See https://github.com/pyannote/pyannote-audio/issues/1370 for more details.
app-1  | 
app-1  |   warnings.warn(
app-1  | /Whisper-WebUI/venv/lib/python3.11/site-packages/pyannote/audio/models/blocks/pooling.py:104: UserWarning: std(): degrees of freedom is <= 0. Correction should be strictly less than the reduction factor (input numel divided by output numel). (Triggered internally at ../aten/src/ATen/native/ReduceOps.cpp:1823.)
app-1  |   std = sequences.std(dim=-1, correction=1)
app-1  | Error transcribing file: module 'numpy' has no attribute 'NAN'
app-1  | /Whisper-WebUI/venv/lib/python3.11/site-packages/torch/cuda/memory.py:365: FutureWarning: torch.cuda.reset_max_memory_allocated now calls torch.cuda.reset_peak_memory_stats, which resets /all/ peak memory stats.
app-1  |   warnings.warn(
app-1  | Traceback (most recent call last):
app-1  |   File "/Whisper-WebUI/venv/lib/python3.11/site-packages/gradio/queueing.py", line 624, in process_events
app-1  |     response = await route_utils.call_process_api(
app-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
app-1  |   File "/Whisper-WebUI/venv/lib/python3.11/site-packages/gradio/route_utils.py", line 323, in call_process_api
app-1  |     output = await app.get_blocks().process_api(
app-1  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
app-1  |   File "/Whisper-WebUI/venv/lib/python3.11/site-packages/gradio/blocks.py", line 2015, in process_api
app-1  |     result = await self.call_function(
app-1  |              ^^^^^^^^^^^^^^^^^^^^^^^^^
app-1  |   File "/Whisper-WebUI/venv/lib/python3.11/site-packages/gradio/blocks.py", line 1562, in call_function
app-1  |     prediction = await anyio.to_thread.run_sync(  # type: ignore
app-1  |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
app-1  |   File "/Whisper-WebUI/venv/lib/python3.11/site-packages/anyio/to_thread.py", line 56, in run_sync
app-1  |     return await get_async_backend().run_sync_in_worker_thread(
app-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
app-1  |   File "/Whisper-WebUI/venv/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 2441, in run_sync_in_worker_thread
app-1  |     return await future
app-1  |            ^^^^^^^^^^^^
app-1  |   File "/Whisper-WebUI/venv/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 943, in run
app-1  |     result = context.run(func, *args)
app-1  |              ^^^^^^^^^^^^^^^^^^^^^^^^
app-1  |   File "/Whisper-WebUI/venv/lib/python3.11/site-packages/gradio/utils.py", line 865, in wrapper
app-1  |     response = f(*args, **kwargs)
app-1  |                ^^^^^^^^^^^^^^^^^^
app-1  |   File "/Whisper-WebUI/modules/whisper/base_transcription_pipeline.py", line 228, in transcribe_file
app-1  |     transcribed_segments, time_for_task = self.run(
app-1  |                                           ^^^^^^^^^
app-1  |   File "/Whisper-WebUI/modules/whisper/base_transcription_pipeline.py", line 164, in run
app-1  |     result, elapsed_time_diarization = self.diarizer.run(
app-1  |                                        ^^^^^^^^^^^^^^^^^^
app-1  |   File "/Whisper-WebUI/modules/diarize/diarizer.py", line 66, in run
app-1  |     diarization_segments = self.pipe(audio)
app-1  |                            ^^^^^^^^^^^^^^^^
app-1  |   File "/Whisper-WebUI/modules/diarize/diarize_pipeline.py", line 38, in __call__
app-1  |     segments = self.model(audio_data, min_speakers=min_speakers, max_speakers=max_speakers)
app-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
app-1  |   File "/Whisper-WebUI/venv/lib/python3.11/site-packages/pyannote/audio/core/pipeline.py", line 326, in __call__
app-1  |     return self.apply(file, **kwargs)
app-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^
app-1  |   File "/Whisper-WebUI/venv/lib/python3.11/site-packages/pyannote/audio/pipelines/speaker_diarization.py", line 578, in apply
app-1  |     discrete_diarization = self.reconstruct(
app-1  |                            ^^^^^^^^^^^^^^^^^
app-1  |   File "/Whisper-WebUI/venv/lib/python3.11/site-packages/pyannote/audio/pipelines/speaker_diarization.py", line 403, in reconstruct
app-1  |     clustered_segmentations = np.NAN * np.zeros(
app-1  |                               ^^^^^^
app-1  |   File "/Whisper-WebUI/venv/lib/python3.11/site-packages/numpy/__init__.py", line 410, in __getattr__
app-1  |     raise AttributeError("module {!r} has no attribute "
app-1  | AttributeError: module 'numpy' has no attribute 'NAN'
```

**Comment by xezpeleta** [comment]
The solution is to upgrade pyannote-audio to 3.3.2

https://github.com/pyannote/pyannote-audio/issues/1758
