### ISSUE TITLE
    from uvr.models import MDX, Demucs, VrNetwork, MDXC ModuleNotFoundError: No module named 'uvr'

### ISSUE THREAD

**Issue by dshwei** [jhj0517/Whisper-WebUI#412]
Traceback (most recent call last):
  File "/home/project/Whisper-WebUI/app.py", line 11, in <module>
    from modules.whisper.whisper_factory import WhisperFactory
  File "/home/project/Whisper-WebUI/modules/whisper/whisper_factory.py", line 6, in <module>
    from modules.whisper.faster_whisper_inference import FasterWhisperInference
  File "/home/project/Whisper-WebUI/modules/whisper/faster_whisper_inference.py", line 17, in <module>
    from modules.whisper.base_transcription_pipeline import BaseTranscriptionPipeline
  File "/home/project/Whisper-WebUI/modules/whisper/base_transcription_pipeline.py", line 12, in <module>
    from modules.uvr.music_separator import MusicSeparator
  File "/home/project/Whisper-WebUI/modules/uvr/music_separator.py", line 11, in <module>
    from uvr.models import MDX, Demucs, VrNetwork, MDXC
ModuleNotFoundError: No module named 'uvr'

**Comment by jhj0517** [comment]
Hi, The `uvr` package is installed via the `git`+`pip`, I suspect this problem is caused by `git` not being installed properly.

Can you check if the `git` is installed in your environment by typing this in the terminal?

```
git --version
```

**Comment by Navalha54783** [comment]
I'm having the same issue. Also i check the git version ---> git version 2.34.1

**Comment by jhj0517** [comment]
@Hans-Na Can I know what Python version you are using?
I'm using python 3.11.1 with git and couldn't reproduce it.
