### ISSUE TITLE
Errors while installing, WIndows 10, Python 3.13

### ISSUE THREAD

**Issue by Pekkape** [jhj0517/Whisper-WebUI#419]
**Which OS are you using?**
 - OS: [e.g. iOS or Windows.. If you are using Google Colab, just Colab.]
 - Windows 10, Python 3.13

Got Errors when I tried to install the Wedui. I did run update.bat first and then install.bat

Collecting git+https://github.com/jhj0517/jhj0517-whisper.git (from -r requirements.txt (line 8))
  Cloning https://github.com/jhj0517/jhj0517-whisper.git to c:\users\pekka\appdata\local\temp\pip-req-build-chnpq7kf
  Running command git clone --filter=blob:none --quiet https://github.com/jhj0517/jhj0517-whisper.git 'C:\Users\pekka\AppData\Local\Temp\pip-req-build-chnpq7kf'
  Resolved https://github.com/jhj0517/jhj0517-whisper.git to commit 197244318d5d75d9d195bff0705ab05a591684ec
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [25 lines of output]
      <string>:5: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
      Traceback (most recent call last):
        File "D:\DL_Skyrim\XTTS\Whisper-WebUI-Portable-Windows\Whisper-WebUI\venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
          ~~~~^^
        File "D:\DL_Skyrim\XTTS\Whisper-WebUI-Portable-Windows\Whisper-WebUI\venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ~~~~^^^^^^^^^^^^^^^^^^^^^^^^
        File "D:\DL_Skyrim\XTTS\Whisper-WebUI-Portable-Windows\Whisper-WebUI\venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "C:\Users\pekka\AppData\Local\Temp\pip-build-env-use0x2ec\overlay\Lib\site-packages\setuptools\build_meta.py", line 334, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\pekka\AppData\Local\Temp\pip-build-env-use0x2ec\overlay\Lib\site-packages\setuptools\build_meta.py", line 304, in _get_build_requires
          self.run_setup()
          ~~~~~~~~~~~~~~^^
        File "C:\Users\pekka\AppData\Local\Temp\pip-build-env-use0x2ec\overlay\Lib\site-packages\setuptools\build_meta.py", line 522, in run_setup
          super().run_setup(setup_script=setup_script)
          ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\pekka\AppData\Local\Temp\pip-build-env-use0x2ec\overlay\Lib\site-packages\setuptools\build_meta.py", line 320, in run_setup
          exec(code, locals())
          ~~~~^^^^^^^^^^^^^^^^
        File "<string>", line 21, in <module>
        File "<string>", line 11, in read_version
      KeyError: '__version__'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

Requirements installation failed. please remove venv folder and run install.bat again.
Press any key to continue . . .

**Comment by jhj0517** [comment]
Hi @Pekkape.

> Windows 10, Python 3.13

Currently there's a version restriction with `python`, you have to use 3.10<= `python` < 3.13 :  https://github.com/OpenNMT/CTranslate2/issues/1817 

Would you try again with `python` between 3.10 ~ 3.12 ? 3.12.x should work fine: 
- https://www.python.org/downloads/release/python-3120/
