### ISSUE TITLE
Recording with Mic doesnt work

### ISSUE THREAD

**Issue by tingtongdpnw** [jhj0517/Whisper-WebUI#75]
Im using Ubuntu 22.04 LTS.

Once i click on the button "Record from microphone", i cant stop the recording, by pressing the button again (nothing happens).
And it also doesnt record and i get following error:

`Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Traceback (most recent call last):
  File "/home/b/Whisper-WebUI/venv/lib/python3.10/site-packages/gradio/routes.py", line 439, in run_predict
    output = await app.get_blocks().process_api(
  File "/home/b/Whisper-WebUI/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1389, in process_api
    result = await self.call_function(
  File "/home/b/Whisper-WebUI/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1094, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/home/b/Whisper-WebUI/venv/lib/python3.10/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/home/b/Whisper-WebUI/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2134, in run_sync_in_worker_thread
    return await future
  File "/home/b/Whisper-WebUI/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 851, in run
    result = context.run(func, *args)
  File "/home/b/Whisper-WebUI/venv/lib/python3.10/site-packages/gradio/utils.py", line 704, in wrapper
    response = f(*args, **kwargs)
  File "/home/b/Whisper-WebUI/modules/faster_whisper_inference.py", line 291, in transcribe_mic
    self.remove_input_files([micaudio])
  File "/home/b/Whisper-WebUI/modules/base_interface.py", line 19, in remove_input_files
    if not os.path.exists(file_path):
  File "/usr/lib/python3.10/genericpath.py", line 19, in exists
    os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
`

Thanks for the help.

**Comment by jhj0517** [comment]
@tingtongdpnw, It seems to be a different temp file path problem on Ubuntu. 
I tried to fix it in #87, can you check the latest version?

**Comment by jhj0517** [comment]
This should be resolved now, 
please feel free to re open it if the issue persists.
