### ISSUE TITLE
Error transcribing file on line 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by Hamzailer** [jhj0517/Whisper-WebUI#97]
**Which OS are you using?**
 - OS: Windows 10

Error transcribing file on line 'NoneType' object is not iterable
C:\Users\Hamzailer\Downloads\Whisper-WebUI-master\venv\Lib\site-packages\torch\cuda\memory.py:330: FutureWarning: torch.cuda.reset_max_memory_allocated now calls torch.cuda.reset_peak_memory_stats, which resets /all/ peak memory stats.
  warnings.warn(
Traceback (most recent call last):
  File "C:\Users\Hamzailer\Downloads\Whisper-WebUI-master\venv\Lib\site-packages\gradio\queueing.py", line 495, in call_prediction
    output = await route_utils.call_process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Hamzailer\Downloads\Whisper-WebUI-master\venv\Lib\site-packages\gradio\route_utils.py", line 232, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Hamzailer\Downloads\Whisper-WebUI-master\venv\Lib\site-packages\gradio\blocks.py", line 1561, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Hamzailer\Downloads\Whisper-WebUI-master\venv\Lib\site-packages\gradio\blocks.py", line 1179, in call_function
    prediction = await anyio.to_thread.run_sync(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Hamzailer\Downloads\Whisper-WebUI-master\venv\Lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Hamzailer\Downloads\Whisper-WebUI-master\venv\Lib\site-packages\anyio\_backends\_asyncio.py", line 2144, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "C:\Users\Hamzailer\Downloads\Whisper-WebUI-master\venv\Lib\site-packages\anyio\_backends\_asyncio.py", line 851, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Hamzailer\Downloads\Whisper-WebUI-master\venv\Lib\site-packages\gradio\utils.py", line 678, in wrapper
    response = f(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Hamzailer\Downloads\Whisper-WebUI-master\modules\faster_whisper_inference.py", line 127, in transcribe_file
    self.remove_input_files([fileobj.name for fileobj in fileobjs])
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not iterable

**Comment by jhj0517** [comment]
Hi @Hamzailer, Thanks for pointing this out. 
It seems like [faster-whipser](https://github.com/SYSTRAN/faster-whisper) has released new version 4 days ago and is not compatible with existing CUDA.
- related issue:
[faster-whisper #717](https://github.com/SYSTRAN/faster-whisper/issues/717)

So I downgraded the faster-whisper version. Can you try the lastest version?
You can test the latest version of this web-ui with :
```
# After activating venv
pip uninstall faster-whisper
pip install faster-whisper==0.10.1
```
Or you can just remove the whole venv folder and run install.bat again.

**Comment by Hamzailer** [comment]
It works now! Thanks for the good work.
